README.md, addons/dialogs/Nodes/Portrait.gd, addons/dialogs/dialog_character_resource.gd, addons/dialogs/dialog_node.gd, addons/dialogs/dialog_resource.gd
This PR removes the requirement for the developer to create auto-loaded `global.gd` and `characters.gd` scripts. The reason for doing so is that they are both very common names which may result in clashes in some projects, and also that creating extra auto-loaded singleton classes to fuel the dialog system does not seem like the best approach.
This PR proposes a cleaner solution using custom Godot Resources.
Namely a `DialogResource` which contains a reference to an external Json file for the dialog, a `Dictionary` of key/value custom variables, and an `Array` of `DialogCharacterResource` references.
And a `DialogCharacterResource` which contains a Name, an Image and Color.
Instead of creating a `global.gd` script that returns custom variables and a `characters.gd` script returning a …
=> Adds Resource Files

CREDITS.md, addons/dialogic/Images/plugin-editor-icon.svg, addons/dialogic/Images/plugin-editor-icon.svg.import, addons/dialogic/dialogic.gd
This updates the editor icon to have a more professional look and feel. Borrowed an icon from flaticon, so I've added a credits document (which is required to freely use their icons).
Here's an example of what it looks like:
=> Add a proper editor icon

addons/dialogic/Nodes/dialog_node.gd
No matter what mode the mouse was in before the dialog appeared, it has to be visible in order to select options during dialogs.
These changes makes sure the mouse is visible during selection of options, and reverts it back to the last state after selection is done (which may still be visible, depending on game type)
=> Make sure the mouse is always visible during selection

addons/dialogic/Nodes/dialog_node.gd
I am not fully sure if this approach is ideal (as this dialogue system could be used in games without reliance on mouse input), however this should guarantee the mouse mode is not set to "null" at the very least.
Fixes https://github.com/coppolaemilio/dialogic/issues/38
=> Fix set_mouse_mode being called with null last_mouse_mode

addons/dialogic/Editor/Pieces/Common/ConditionPicker.gd, addons/dialogic/Editor/Pieces/Common/ConditionPicker.tscn, addons/dialogic/Editor/Pieces/IfCondition.gd, addons/dialogic/Editor/Pieces/IfCondition.tscn, addons/dialogic/Nodes/dialog_node.gd
This pull request adds support for more conditions in if statements, as requested in issue https://github.com/coppolaemilio/dialogic/issues/80.
This adds a new scene, `ConditionPicker` to allow selecting conditions, used only in the `IfCondition` Scene. It follows the same structure as the `DefinitionPicker` scene.
Conditions can be saved and loaded back like definitions and values.
Supported conditions are:
```
==
!=
>
>=
<
<=
```
=> Add more 'if' conditions

addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Other/dialogic_class.gd
This allows users to use their own custom dialog scene. The scene should probably be inherited from the base `Dialog.tscn` to ensure compatibility.
I also set the `debug_mode` variable to false by default and made it the third param. If a user wants to set it to `true` and not pass in a custom scene, then user can set it to the node that is returned by the method. It would be a lot easier if Godot had kwargs, but it doesn't yet.
=> Add dialog_scene_path param

addons/dialogic/Other/DialogicUtil.gd
Removed usage of `dir_exists` as it didn't seem to work on exported games
I rewrote the `listdir` function to follow the [official documentation](https://docs.godotengine.org/en/stable/classes/class_directory.html#directory) 
Closes #86
=> fix character exporting

addons/dialogic/Nodes/dialog_node.gd
If condition and definition values are valid floats,
then make the conversion on floats.
Otherwise, fallback to string comparison.
This adresses the issue we talked in the [PR](
https://github.com/coppolaemilio/dialogic/pull/81#issuecomment-800489767)
=> fix number comparison

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicUtil.gd
Allows showing inline variables using `${variable_name}` inside a text message.
Parsing takes place before each text update, not just in the initial timeline loading.
This allows showing dynamic variables inside a dialogue.
Variable values are inserted before glossary parsing, allowing dynamic glossary text.
For example, if `test_value`'s value is `test_gloss`, then putting `${test_value}` inside a text/question will show test_gloss and enable the glossary popup on the word.
Might help solve #84.
=> add inline variables support

addons/dialogic/Editor/DefinitionEditor/DefinitionEditor.gd, addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/MasterTree/MasterTree.gd, addons/dialogic/Editor/Pieces/Common/DefinitionPicker.gd, addons/dialogic/Editor/Pieces/IfCondition.gd, addons/dialogic/Editor/Pieces/SetValue.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Other/DialogicDefinitionsSingleton.gd, addons/dialogic/Other/DialogicDefinitionsUtil.gd, addons/dialogic/Other/DialogicResources.gd, addons/dialogic/Other/DialogicSingleton.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Other/timeline_picker.gd, addons/dialogic/dialogic.gd
Definitions and current timeline are kept in memory inside a singleton, and saved to disk when needed.
This data is only saved to the config file on timeline end/start.
While in the editor, default values are loaded as I can't seem to make the saves singleton load.
User can request a definitions reset either by a dedicated function, or by passing an argument to the start method.
Current timeline is saved so user can read it while running or load it back on next run. This feature combined with definitions saving makes a complete save/restore system, in which users can exit mid-timeline without negative effects.
I also added a lot of utility functions in `DialogicClass.gd`, to allow the user to edit and query variables and glossary definitions. It only repeats functions in the singleton, …
=> Synchronize definitions and timeline saving

addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/EditorView.tscn, addons/dialogic/Editor/MasterTree/MasterTree.gd, addons/dialogic/Editor/Pieces/AudioBlock.tscn, addons/dialogic/Editor/Pieces/ChangeScene.tscn, addons/dialogic/Editor/Pieces/ChangeTimeline.tscn, addons/dialogic/Editor/Pieces/CharacterJoinBlock.tscn, addons/dialogic/Editor/Pieces/CharacterLeaveBlock.tscn, addons/dialogic/Editor/Pieces/Choice.tscn, addons/dialogic/Editor/Pieces/CloseDialog.tscn, addons/dialogic/Editor/Pieces/Common/Spacer.tscn, addons/dialogic/Editor/Pieces/EmitSignal.tscn, addons/dialogic/Editor/Pieces/EndBranch.tscn, addons/dialogic/Editor/Pieces/IfCondition.tscn, addons/dialogic/Editor/Pieces/Question.tscn, addons/dialogic/Editor/Pieces/SceneEvent.tscn, addons/dialogic/Editor/Pieces/SetTheme.tscn, addons/dialogic/Editor/Pieces/SetValue.tscn, addons/dialogic/Editor/Pieces/TextBlock.tscn, addons/dialogic/Editor/Pieces/WaitSeconds.tscn, addons/dialogic/Editor/Pieces/selected_styleboxflat.tres, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn
This PR adds buttons to fold/unfold all nodes in a timeline. It also adds the possibility to select pieces. When selecting a piece, it will change color and adding a node will add it just bellow the selected piece. Clicking again a node will deselect it.
I did all the logic inside `TimelineEditor.gd`, so this will work on any piece as long as it has a `PanelContainer` node just bellow the root.
I think we could do the same for the `DragController`: instead of adding the node on each piece, control everything from `TimelineEditor.gd`, this will be easier to maintain.
If you want to change how selected items appear, you can edit the style in `res://addons/dialogic/Editor/Pieces/selected_styleboxflat.tres`
This does not touch resources handling so it is not breaking.
=> Improve timeline editor controls

addons/dialogic/Nodes/Portrait.gd
Removed the hardcoded offset of -130 and replaced it by 0. This makes it easier to use custom offsets.
Closes #101
=> align portraits to the bottom of the screen

addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd, addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn, addons/dialogic/Nodes/dialog_node.gd
This PR moves input handling inside the `_input(event)` function, and adds a setting to control propagating to the rest of the tree (on by default).
Closes #47
=> Add setting to control input propagating

README.md, addons/dialogic/BackgroundMusic.gd, addons/dialogic/BackgroundMusic.tscn, addons/dialogic/Dialog.tscn, addons/dialogic/Editor/Pieces/AudioBlock.gd, addons/dialogic/Editor/Pieces/AudioBlock.tscn, addons/dialogic/Editor/Pieces/BackgroundMusic.gd, addons/dialogic/Editor/Pieces/BackgroundMusic.tscn, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn, addons/dialogic/Nodes/dialog_node.gd
This adds a new timeline piece allowing to set background music.
Music crossfade on change, and fade out on stop.
To stop music, simply put a BackgroundMusic node without a file selected.
Closes #117
=> add basic background music controls

README.md, addons/dialogic/Editor/Pieces/Common/OperationPicker.gd, addons/dialogic/Editor/Pieces/Common/OperationPicker.tscn, addons/dialogic/Editor/Pieces/SetValue.gd, addons/dialogic/Editor/Pieces/SetValue.tscn, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicSingleton.gd
This PR adds the possibility to make basic calculations between a variable and a constant.
Supported operations are `=`, `+`, `-`, `*`, `/`.
Values are converted to numbers before the operation. If both values cannot be converted to number, only `=` and `+` operations are allowed, the others are ignored.
This is not breaking, all previous `Set value` events should be converted as simple `=` events.
Closes #119
=> Set value operations

addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicSingleton.gd
We only reload saves if the user wants to reset them.
This allows editing definitions before adding the node to the tree
Closes #125
=> do not reload saves on node init unless forced

addons/dialogic/Dialog.tscn, addons/dialogic/Nodes/BackgroundMusic.gd, addons/dialogic/Nodes/BackgroundMusic.tscn, addons/dialogic/Nodes/dialog_node.gd
Make sure audio streams start muted for first crossfade.
Keep current track in memory to prevent crossfade to same music.
Closes #121
=> Fix background music fade

addons/dialogic/Editor/Pieces/CallNode.gd, addons/dialogic/Editor/Pieces/CallNode.tscn, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn, addons/dialogic/Nodes/dialog_node.gd
Hi guys, I hope you are not mad at me, but I created a new event node for the timeline to call arbitrary node methods, because I needed it badly. I couldn't decide if I just create a workaround or just contribute instead. I do not want to take over your project, but maybe you find this handy and are considering to add it? It was not hard to do, so I am not mad if you decline it.
**Summary**:
I created a new event node call "Call Node". You can setup the node to call with a default Godot NodePath and a method name. In addition you can add arguments as well. The Timeline will execute those methods and even wait for completion, if the method in question is async and/or yielding.
**Usage**:
Add "Call Node" to your timeline. Change "Target Node" in GodotNodePath format. (e.g. …
=> Added call-node feature

addons/dialogic/Editor/TimelineEditor/TimelineArea.gd
This fixes #138 
Drop events now get canceled when the user releases the left mousebutton while still dragging outside the scroll area
=> fix #138 cancel drop events

addons/dialogic/Editor/MasterTree/MasterTree.gd, addons/dialogic/Other/inspector_timeline_picker.gd, addons/dialogic/Other/timeline_picker.gd, addons/dialogic/dialogic.gd
This PR for #144 implements a button next to the timeline selection inspector plugin
to directly jump to the timeline editor and selecting the corresponding timeline.
This addon as well adjusts some visual/sizing issues with the original timeline selection MenuButton
Please check that this plugin does not interfere and works as you like before mergin.
Showcase: 
https://streamable.com/yggbm7
=> edit timeline button in timeline inspector plugin

addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
This PR fixes #155 
However, I could not get it to work to deselect on empty space outside of the timeline with the current control structure.
But this fix itself adds enough useability for now
=> Fix #155 deselect timeline item on singleclick

addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/EditorView.tscn, addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Other/DialogicResources.gd
This PR draft implements Milestone Issue #66
You can now duplicate a theme while rightclicking and pressing: duplicate theme
=> duplicating themes [Feature #66]

addons/dialogic/Editor/Pieces/SceneEvent.gd, addons/dialogic/Nodes/dialog_node.gd
This PR implements issue #9
You can now select a tscn file as a background in the Scene Event node.
The scene gets attached as a child of the original background, and removed if you reset it
Showcase:
https://streamable.com/tctp9w
=> allow scenes as backgrounds [Feature #9]

addons/dialogic/Editor/Pieces/TextBlock.gd
This PR fixes #163 
apparently Godot triggers the focus_entered signal on mouse wheel in a lineedit, without actually grabbing focus.
This is a workaround to only listen for left clicks and ignoring other mouse events
=> [Fix #163] select only on left click #workaround

addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
This PR fixes the second part of #162
I chose to only trigger the indent **after** the dragging is done and not on every dragging step to reduce the load on slow computers as @coppolaemilio pointed out
=> [Fix #162] indent after dragging a piece #followup

addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn
This makes the left sidebar in the Timeline editor reziseable. It fixes #123. I don't know why the separation was there in the first place so maybe it's wrong. This is my first pull request ever, so please correct me if I'm doing something wrong.
=> Make the left Sidebar in the Timelineeditor resizable

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- Creating multiple columns for all the tabs
- Creating a section title for each column
- general sorting and reordering of the settings/options
- Renaming the "Auto Color" option to "Use character Color"
- Renaming Text tab to Dialog Text
- Cleaning and reordering the beginnging of the ThemeEditor.gd script (The reference part)
- Fixing the refrences to all the elements in the ThemeEditor.gd script
- Making the tabs always go to the bottom
- moving the "text input" field and the "preview changes" button below the preview and switch them
Preview:
=> Updating the theme-editor design

addons/dialogic/Nodes/dialog_node.gd
(recommended to be used with native buttons from https://github.com/coppolaemilio/dialogic/pull/185 )
Solves #167
=> First choice grabs focus, keyboard/controller can be used to answer

addons/dialogic/Nodes/Portrait.gd
TL;DR: this fix a no reported issue related to the order of the portraits
Apparently there's a bug that causes lost the focus order:
This PR fixes it:
=> Fix the portrait focus order

addons/dialogic/Dialog.tscn, addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicClass.gd
This PR moves the `start` and `start_from_save` methods from `DialogicClass` to `dialogic_node`.
This allows the DIalogicNode to be persistent: no need to delete and create a new node to play a new timeline.
I had to add a new var named `runtime_id` to check if the timeline changed between 2 events. This was necessary when calling start from a signal fired by Dialogic: the new timeline would get loaded, then the index incremented when reaching the end of the signal event, from the previous timeline, skipping the first event from the new timeline.
To make this work I had to refactor a bit the event loading system.
This may need more work, as the DIalogicNode was not designed to be reset.
Example usage:
With DialogNode added to the tree:
The triggering timeline:
After receiving the …
=> move start methods in dialog_node

addons/dialogic/Editor/Pieces/Common/VisibleToggle.gd, addons/dialogic/Editor/Pieces/SceneEvent.gd, addons/dialogic/Editor/Pieces/SceneEvent.tscn
This PR allows the user to clear the selected scene from a scene event, like it can already do with audio events.
I moved the selectors to the header to follow what is already done in audio events. I also replace the LineEdit by a simple label as changing the path from the LineEdit had no effect.
Only Editor UI changed, so this is non breaking.
Closes #192
=> allow clearing scene event

README.md, addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn, addons/dialogic/Editor/Events/CharacterJoinBlock.gd, addons/dialogic/Editor/Events/CharacterJoinBlock.tscn, addons/dialogic/Nodes/Portrait.gd, addons/dialogic/Nodes/dialog_node.gd
This is a simple implementation adding a setting for each character. If enabled the portraits will be mirrored when they are shown on the right or the center-right positions. 
There was a discussion about how to implement this, so if you don't like it, don't merge it.
It should fix #168
=> Mirror portraits setting for characters and the Join event (updated)

addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
I added the mirror option to the dictionary but the timeline didn't expect it. I learned about this while working on the audio events. Sorry I introduced this.
This should fix #216.
=> Join events weren't recognised by the timeline FIX

addons/dialogic/Other/DialogicSharp.cs
Fixes #55 
I haven't tested this extensively yet as I'm just getting started with Dialogic but this works for me to:
* Set and retrieve variable values.
* Show a dialog.
This could use some cleanup like duplicating across the documentation in C#'s format but this seems to be functional at least. It operates in the same way that the static `Dialogic` class works for GDScript.
Example usage (no `using` statements necessary):
```
public override void _Ready()
{
var dialog = DialogicSharp.Start("Greeting", false);
AddChild(dialog);
}
```
=> fix: add a static proxy for C# projects

addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Other/DialogicResources.gd, addons/dialogic/Other/DialogicSharp.cs, addons/dialogic/Other/DialogicSingleton.gd
Fixes #224.
This is my proposal for manual save management. This allows developers to manually handle save data management if they need something more complicated that the autosave provides. This also allows for multiple save states using whatever save mechanism the developer is using already.
Example usage:
```gdscript
Dialogic.set_autosave(false)
var dialogic_data = Dialogic.export()
Dialogic.import(dialogic_data);
```
Dialogic should continue to work the same way unless `set_autosave(false)` is called with one exception:
1. Dialogic will no long pre-emptively create files and folders in `user://dialogic`, instead waiting to create them just in time as it saves state for the first time.
=> Manual save data export/import

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn, addons/dialogic/Nodes/dialog_node.gd
This PR adds the possibility to disable glossary using a theme. This is pretty simple: a checkbox under the glossary tab. The text will not be highlighted and the infobox will not show.
Setting enabled:
Setting disabled:
Closes #220
=> allow hiding glossary in theme settings

addons/dialogic/Editor/Events/Templates/EventTemplate.gd, addons/dialogic/Editor/TimelineEditor/TimelineArea.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
This PR improves drag and drop by reusing event dragging behavior.
Instead of creating a placeholder where the event will be created, the actual event piece is added to the timeline. This event will be ignored when saving unless it is actually dropped (mouse key released). The  event is selected and thus can use the already defined dragging behavior, fixing a lot of issues with moving drag-and-drop events that were already fixed for regular event dragging inside the timeline (see 95d7296ea17b346272a13753b62d92122020301b).
https://user-images.githubusercontent.com/80701113/115136885-0863f480-a023-11eb-8f8b-6a77250426f9.mp4
=> show real event in drag and drop

addons/dialogic/Nodes/dialog_node.gd
This PR moves start and end timeline signals into their own signals, to separate them from events. This will make it easier to use.
=> add timeline start and end signals

addons/dialogic/Editor/Events/ChangeBackground.gd, addons/dialogic/Editor/Events/Common/SecondsSelector.gd, addons/dialogic/Editor/Events/Common/SecondsSelector.tscn, addons/dialogic/Editor/Events/Templates/EventTemplate.gd, addons/dialogic/Editor/Events/WaitSeconds.gd, addons/dialogic/Editor/Events/WaitSeconds.tscn, addons/dialogic/Editor/Events/styles/WaitSeconds.tres, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
This PR makes the `Wait Seconds` event us the new template and helps fixing current issues.
This also changes the template so that it stores the `event_data` variable and implements the `load_data` function. This way, events implementing the template do not have to re-declare the variable and only need to override the function to populate fields. I could have made a new pr just for this but was lazy.
Closes #236
=> make wait seconds use the new template

addons/dialogic/Editor/Events/Templates/EventTemplate.tscn, addons/dialogic/Editor/Events/styles/ChangeBackground.tres, addons/dialogic/Editor/Events/styles/WaitSeconds.tres, addons/dialogic/Editor/Events/styles/selected_styleboxflat_template.tres
This PR makes template items 42 units tall instead of 44, to match non-template events
=> fix event template size

addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd, addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn, addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn, addons/dialogic/Nodes/dialog_node.gd
This PR lets the user use custom choice buttons. The custom scenes can be selected from the theme editor.
The selected scene must implement the `pressed` signal and have the `text` property available, like any component extending `Button`.
No checks are performed, the user is only told in the button/label tooltip in the theme editor. Selecting a scene which does not meet the requirements could crash the game.
Like with native buttons, activating custom buttons in the theme editor disables other controls.
Closes #247
=> add support for custom choice buttons

addons/dialogic/Editor/Events/EmitSignal.tscn
There was just to much confusion.
This is how it looks now:
=> Add explaining label to the Emit Signal event

addons/dialogic/Other/DialogicResources.gd
This PR makes timelines and definitions easier to read and to handle with git. It also sorts object keys to prevent unnecessary changes when simply opening the timeline without modifying it in the editor.
The drawback is the file size, which increases because of the added characters. This PR does not provide any minifying script to run before packing the game.
Closes #269
=> pretty print resources json with sorted keys

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn, addons/dialogic/Nodes/dialog_node.gd, addons/dialogic/Other/DialogicUtil.gd
Hello, Emilio and everyone else! My name is Zak. I have been wanting to add **_Nicknames_** to the project since I tried it out. I call my friends nicknames and it is common in literature and video games as well, so I felt that naturally it should be included. I finally decided to do it myself and I hope everyone else can find some use for them as well as a feature! What this entails is this: **any Nicknames that you give to the character and enable in the editor will also follow auto-color rules**. If you don't have auto-color enabled it does nothing. This is also per character so each one doesn't need to have Nicknames (similar to display names). What is different is that these are not on the name tag and you will not need to go in and manually color nicknames in text events using …
=> Adding Nicknames (New Feature) and fixing auto-color names in text events

addons/dialogic/Nodes/dialog_node.gd
This way you can warn the user that he did not add his node to a canvas layer and that it probably won't show up in the game as expects. 
It is not an automatic way to solve the problem, but a way to tell you what the problem is.
=> Update dialog_node.gd to warn the user when Dialogic node is not child of canvas layer

README.md
Ie this https://dialogic.coppolaemilio.com/#credits is not working due to the dash `-`
I had to remove the ❤️ from credits to make it work.
I also made inline links work.
=> Inline anchors refs don't work

addons/dialogic/Nodes/dialog_node.gd
When loading the timeline directly with GDscript as descriped in the FAQ :
```
func _ready():
var gdscript_dialog = Dialogic.start('')
gdscript_dialog.dialog_script = {
"events":[
{ 'event_id':'dialogic_001', "character": "", "portrait":"", "text": "This dialog was created using GDScript!"}
]
}
add_child(gdscript_dialog)
```
the loading of the timeline is not complete because most of the loading is done in the set_current_dialog function, and that function is only called if the "timeline" attribute is set.
I tried in this PR to create a separate loading method that is called by set_current_dialog and by itself if the timeline is created by GDscript (with empty timeline attribute).
=> Modify loading function to permit direct loading from GDscript

addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd, addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn, addons/dialogic/Nodes/canvas_dialog_node.gd
This is a fix to [Issue]https://github.com/coppolaemilio/dialogic/issues/362)
In the settings editor, you can now choose the layer index which the dialogic's canvas layer will use.
This should prevent dialogues from being rendered behind UI with higher layers.
=> Custom Canvas Layer in settings

.gitattributes
Not sure if this is actually welcome, but this gives a faster and easier install flow where user doesn't need to select what to keep.
Note: this works by removing ignored files from zip downloaded from github. This also affects releases archives, so you might want to keep something like README or LICENSE. But other than that folders like .github and files like .git* are really have no reason to be exported.
Awesome project :)
=> This tells git to ignore certain nonessential files from export allowing for faster installing from AssetLib

addons/dialogic/Other/DialogicClass.gd
Changes the 'find timeline' part of `Dialogic.start()` to filter timelines from `DialogicUtil.get_timeline_list()` by `current_data['files']`, leaving only the relevant ones. Then find the the timeline where name equals end of the path (at this point `p`).
Fixes #451
=> Use last part of path to find specific timeline in 'Dialogic.start()'

addons/dialogic/Nodes/Portrait.gd
Currently the "Don't change" setting isn't handled in the `set_portrait` method and will reset the portrait to the default one.
=> Fixed "Don't change" setting.

addons/dialogic/Nodes/DialogNode.gd
When looking if a character already entered (to update the portrait on text and question events), it checked the character data against the one of the portrait. That didn't work. So now it checks the characters file, which should actually always be the same.
=> Fixing bug that prevented portrait update

addons/dialogic/Documentation/Nodes/DocsMarkdownParser.gd
Previously it only recognized `code`, now it can also do:
```
longer code snippets.
```
They will be slightly indented, we'll see if that's good.
=> Changing the DocsMarkdownParser to understand ``` code as well

addons/dialogic/Documentation/Content/FAQ/CSharp.md, addons/dialogic/Documentation/Content/FAQ/Portraits.md, addons/dialogic/Documentation/Content/FAQ/can-i-use-dialogic-in-my-project.md, addons/dialogic/Documentation/Content/FAQ/create-timeline-using-gdscript.md, addons/dialogic/Documentation/Content/FAQ/how-to-make-dialog-show-up-in-game.md, addons/dialogic/Documentation/Content/FAQ/plugin-shipped-godot.md, addons/dialogic/Documentation/Content/FAQ/resolution-small-dialog-big.md, addons/dialogic/Documentation/Content/FAQ/why-not-graph-nodes.md, addons/dialogic/Documentation/Content/Reference/001.md, addons/dialogic/Documentation/Nodes/DocsTreeHelper.gd, addons/dialogic/Other/DialogicClass.gd
Fixes #521.
Rewrite of the DialogicClass reference to contain all the important methods (and no outdated ones.
Makes the titles of the FAQ pages shorter.
=> Documentation improvements.

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn, addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/TextBubble.gd, addons/dialogic/Nodes/TextBubble.tscn, addons/dialogic/Other/DialogicResources.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Parser/DialogicParser.gd
Unfortunately the RichtTextLabel isn't really able to do this. So I'm using a VBoxContainer for the alignment.
Also I changed how the alignment is saved from string to ints. 
ToDo: Test out how Margin and Padding work now
=> Adding more Alignment options for Dialog Text

addons/dialogic/Other/DialogicSharp.cs
When building a Godot Mono 3.4 project using the library a build error
occurs:
`\addons\dialogic\Other\DialogicSharp.cs(16,102): Optional parameters
must appear after all required parameters`
Made set a default parameter for `dialogScenePath` so that ordering
rules for C# are respected and the library builds when used in a
project.
See C# documentation for more details:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments
=> closes #657 build error for DialogSharp.cs

addons/dialogic/Editor/EditorView.gd
You can now not delete the last theme anymore. Instead the popup will say, you can't. Should fix #466
=> Prevent last theme from being deleted

addons/dialogic/Nodes/DialogNode.gd
Fix for #693
It now checks for current definitions instead of defaults and also checks on text/question event.
=> Fix Definition Portraits

addons/dialogic/Nodes/TextBubble.gd
Know that whenever you made a regex that looks like it works: 
-> IT DOESN'T
You can be sure that there is something you missed.
The s in the beginning of speed and signal where picked up as a [s] (strikethrough) tag from bbcode (which get's removed before checking for the dialogic tags. So it didn't consider these as tags.
This should fix #660
=> Fix TextBubble BBCode/Tag Regex

addons/dialogic/Documentation/Content/Reference/001.md, addons/dialogic/Other/DialogicClass.gd
When using Dialogic with multiple save games we need to somehow "reset" Dialogic, as each save game will have its own state that will be populated on savegame load. Currently, it is difficult to reset variables from gdscript so I introduced a new utility method to do exactly that.
=> add method to clear all variables

addons/dialogic/Nodes/TextBubble.gd
This is a simple fix that prevents the [img] bbcode from breaking the game (fixes #714). It's not perfect, because it means after the image all checks for a specific character will be off. That's because the image counts as a "visible_character" but has no  character in the $RichTextLabel.text property.
=> Add check for correct text length

addons/dialogic/Nodes/canvas_dialog_node.gd
Should fix #717
It was due to the canvas layer node connecting on ready but being further up in the tree than the Dialog Node an thus connecting a moment after the DialogNode ready function.
=> Fix signal connection delay

addons/dialogic/Nodes/DialogNode.gd
While testing I noticed that if you have a empty `Change Timeline` event it will result in crash, while it should actually just ignore it.
=> Check if Change Timeline has a selected timeline

addons/dialogic/Nodes/DialogNode.gd
Added a 'catch' for extra input while the text is typing but before the choices appear
Prevent the Idle state from occurring if the event contains options
=> Fix for issue 633

addons/dialogic/Example Assets/CustomEvents/event_yourname_000.gd
Updated event generation to use the state system rather than the old Booleans
=> Updated Event Generation

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn, addons/dialogic/Nodes/TextBubble.gd
Solves https://github.com/coppolaemilio/dialogic/issues/677
Adds a theme option to hide name labels altogether.
The option can be found in the new `Behaviour` section inside the `Name label` tab in the Theme editor, called: `Hide name labels`. 
By toggling this option on, all other inputs in the tab will be disabled as any changes to those fields will not render any result.
https://user-images.githubusercontent.com/1572060/150575195-ac207bca-5304-46f1-b59b-755ec0613418.mp4
=> Add theme option to hide name labels

addons/dialogic/Editor/Events/CharacterJoin.tscn, addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/CharacterJoinSettings.tscn, addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterJoinSettings.gd, addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/Portrait.gd, addons/dialogic/Nodes/Portrait.tscn, addons/dialogic/Other/DialogicUtil.gd
Adds a body to the character join event that allows to select an animation and it's length as well as a fake z-index. 
Should fix #712 and somewhat #639
I think it would be nice to be able to change the default animation. 
Also I noticed that you could make a character join multiple times right now, because it somehow wouldn't recognize that it was already joined, so I updated that. 
Characters will NOT come to the front anymore when talking. if this is wanted again, it should be relatively easy to add an option.
=> Animation and z_index for the Character Join Event 

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/MasterTree/MasterTree.gd, addons/dialogic/Nodes/Background.gd, addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/TextBubble.gd
Sorry for doing multiple things in the same PR. Mainly things I noticed during testing with the Test Project. 
- Character Editor Actual Size preview now mirrors if mirror portraits is enabled
- Name Label padding option now also affects the top
- You can now duplicate the default theme as well (#750)
- Fix for custom theme didn't quite work as expected
- removed a print statement
- Fixes background fading (#752)
=> Fixes for different things

addons/dialogic/Nodes/TextBubble.gd
Fix for #756. This PR allows any amount of white space (excluding newlines) anywhere within the square brackets, as in:
`[ signal = test ]`.
It also updates the comment mentioning this regex.
=> allow spacing in commands

addons/dialogic/Nodes/DialogNode.gd
Previously it would only check the display name when updating the Name Label and ignored the display name bool.
=> Make sure the Display Name Bool does something

addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Parser/DialogicParser.gd
This is to add the features for getting/setting and display in a text block for a variable by the folder path name, as in #746. Also, as this was based on the function for doing so in timelines, fixes a bug in the existing timeline folder search code as mentioned in #739 which prevented either that or the new variable search to work on the root of the folder tree
Also included is the command to test if a timeline exists, as requested in #739
=> Fixes for addressing Variables and Timelines by folder path

addons/dialogic/Nodes/DialogProxy.gd
The proxy node still had the reset_saves property but it wouldn't do anything anymore, because we removed the reset_saves parameter of the start function. This should make it work again meaning it resets all changes to definitions.
=> Add reset-saves functionality to Proxy node

addons/dialogic/Other/DialogicClass.gd
It will just use the "ui_accept" action when default is selected. 
For 2.0 I suggest just removing the Default option, but that woult be to much work for 1.4.
Should fix #740
=> Add "[Default]" functionality to action key

addons/dialogic/Editor/Events/Parts/Text/EventPart_TextEditor.gd, addons/dialogic/Editor/Events/Parts/Text/TextEditor.tscn
Should help with #704
I also decided to show the line numbers again, because I just like that more.
=> Make TextBox wrap when it get's to big

addons/dialogic/Editor/MasterTree/MasterTree.gd
A simple attempt to make the file names a bit easier to find out, so you don't have to open all files and look at their content to find out what file is what. Somewhat related to #496
Also updated the rmb popup looks of the menus on the MasterTree.
=> Add right-click options to copy file names

addons/dialogic/Editor/TimelineEditor/TimelineArea.gd
Arcs on the first indentation level would be messed up.
Also the draw call would just return if two choice events followed each other.
=> Fix mistakes from the line update 

addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd, addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Other/DialogicUtil.gd
There is now a dialogic_default_action automatically created in the InputMap. It is now also the new default. 
Unfortunately you have to force the editor to update by reloading the project or adding another action to able to see this action. But this is only a problem the first time you open the project (or if you delete the action).
Also the editors internal InputMap will no longer be messed up when setting the action key (#736).
=> Add new dialogic_default_action and fix bug #736

addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/TextBubble.gd
The way the fade in animation was working, together with some calls to TextBubble.update_text("") meant, that on the first event the state would get messed up. I have reworked this whole procedure to something that is cleaner imo and removes these problems.  This should fix #794
=> Rework the states of the dialog box fade in animation

addons/dialogic/Editor/Events/Parts/EventPart.gd, addons/dialogic/Editor/Events/Parts/Text/EventPart_TextAndVoicePicker.gd, addons/dialogic/Editor/Events/Parts/Text/EventPart_TextEditor.gd, addons/dialogic/Editor/Events/Templates/EventBlock.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
This new function (focus()) is called when an event is newly created on all the direct EventParts of the event (body/header). This allows them to do anything they would like. It' s not called when the timeline is loaded. 
This PR also implements this on the TextAndVoicePicker and it's sub-event-part the TextEditor to make it focus the TextEdit when you create the Text or Question event. This fixes #811
=> Add overridable focus() function for EventParts and use it on Text Event

addons/dialogic/Nodes/DialogNode.gd
Discovered this bug while working on the VN-template. When you loaded dialog it will first start the "[No Timeline Specified]" stuff, because the load_from_save() thing waits until "_ready". Then it will overwrite this. But because the fade was triggered before it would switch back and show the "[No Timeline Specified]" again.
=> Make sure fade in doesn't mess with dialogs loaded from save

addons/dialogic/Documentation/Content/Changelog.md, addons/dialogic/Documentation/Content/Tutorials/Updating.md, addons/dialogic/Editor/Events/Parts/CallNode/CallNodePicker.tscn, addons/dialogic/Editor/Events/Parts/CallNode/EventPart_CallNodePicker.gd, addons/dialogic/Nodes/DialogNode.gd
This makes call event pass each argument in the array instead of passing the whole array.
As an example, consider call event `my_method` with `["1","2","3"]` values to an arbitrary node
```
func my_method(args) <- Current behaviour: call event pass the whole array, so you need to split it manually
```
```
func my_method(arg1, arg2, arg3) <- PR behaviour: each value in the array is passed as an argument
```
I consider this can be annoying to people that already uses call event and split arguments manually, so maybe thay should be notified about this change? No idea
=> Replace `call` with `callv` in event 042

addons/dialogic/resources/event_class.gd
This is part of #869 wich adds Event class script.
I'll try to connect this class with timeline editor, but if I don't find an easy way to do it, I'll just change the timeline editor load behaviour
=> Add Event class

addons/dialogic/Other/export_plugin.gd
Fix for the android export issue I was experiencing
=> Exclude android builds from json/cfg fill

addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn, addons/dialogic/Nodes/DialogNode.gd
The setting will set the dialog nodes controls mouse_filter to MOUSE_FILTER_IGNORE.
This enables you to add other clickable elements and buttons in the background of your scene.
=> Add setting to disable the mouse block of the dialog node 

Emilio.dch, John.dch, addons/dialogic/Editor/CharacterEditor.gd, addons/dialogic/Editor/Common/Toolbar.gd, addons/dialogic/Editor/Common/Toolbar.tscn, addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/EditorView.tscn, addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd, addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn, addons/dialogic/Editor/Events/Fields/Number.gd, addons/dialogic/Editor/Events/Fields/Number.tscn, addons/dialogic/Editor/Events/Fields/OptionSelector.gd, addons/dialogic/Editor/Events/Fields/OptionSelector.tscn, addons/dialogic/Editor/Events/Templates/EventNode.gd, addons/dialogic/Editor/Events/test.gd, addons/dialogic/Editor/Events/text.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/CharacterResourceSaver.gd, addons/dialogic/Resources/Events/event_character.gd, addons/dialogic/Resources/Events/event_comment.gd, addons/dialogic/Resources/Events/event_text.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd, addons/dialogic/Resources/character.gd, addons/dialogic/Resources/default_event.gd, addons/dialogic/Resources/event.gd, timelines/Chapter1.dtl, timelines/Chapter1.timeline
I added a (*) mark to the resource name in the toolbar, if it was edited. 
Adds a character resource as well as a CharcacterResourceLoader and a CharacterResourceSaver. I'm not yet sure in what format it would be best to save the character (currently the values are just stored line by line), maybe also in a way that is easy to edit from the outside. These resources are stored as '.dch' files.
I've changed the extension of the timeline resource to '.dtl'. Thus I had to replace the test timelines.
You can now create new character resources with a button from the toolbar. There isn't really an character editor yet, although there is a placeholder node managing the creation.
To simplify the code I moved the EditorFileDialog to be a child of the EditorView so that it can be used by all the …
=> Improvements (including Characters, Resource Picker, Changed Extensions)

addons/dialogic/Nodes/TextBubble.gd
If your font use an outline, each beginning row will cut this outline.
Checking "clip_content" to false fix this "bug".
=> Remove clip content to prevent outlining cut.

addons/dialogic/Editor/Events/BranchEnd.gd, addons/dialogic/Editor/Events/Fields/SinglelineText.tscn, addons/dialogic/Editor/Events/Templates/EventNode.gd, addons/dialogic/Editor/Events/Templates/EventNode.tscn, addons/dialogic/Editor/TimelineEditor/TimelineArea.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Other/DefaultDialogNode.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/Events/event_condition.gd, addons/dialogic/Resources/Events/event_end_branch.gd, addons/dialogic/Resources/Events/event_text.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd, timelines/Chapter1.dtl
Adds a new condition event. Conditions can be anything the Expression class can parse INCLUDING methods. Currently you can not use variables oc and there is only a text input. 
Conditions should work as expected in game, but I could be wrong.
The condition and choice event can now be folded. The hiding logic is done in `TimelineEditor.indent_events()`. More info in the commit.
You can now delete and undo the deletion again. Duplication, copy/paste/cut are on the todo list.
- added a timeline_ended signal to the DialogicGameHandler and made the preview scene hide on timeline end
- updated the single-line style to be the same as the resource picker. not optimal, but better looking than before. Sorry UI/UX is not my concern right now.
=> Dialogic 2.0: Condition event and folding (and more)

addons/dialogic/Editor/Events/BranchEnd.gd, addons/dialogic/Editor/Events/BranchEnd.tscn, addons/dialogic/Editor/Events/Fields/OptionSelector.gd, addons/dialogic/Editor/Events/Fields/OptionSelector.tscn, addons/dialogic/Editor/Events/Templates/EventNode.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Resources/Events/event_condition.gd, addons/dialogic/Resources/Events/event_end_branch.gd
Adds a ConditionType to the condition event that is either IF, ELIF, or ELSE.
Like before most of the acutal LOGIC is done by the end branch event.
You cannot add elif and else events manually (in the editor), only by using the buttons on the end branch events of if and elif events.
Currently the else event still shows an input for a condition (even though it is ignored). This will change when I add the simplified condition picker.
Please test this a lot, especially together with choices and questions to make sure the logic I implemented for finding the next right event after an end_branch_event is correct!
=> 2.0: Add elif and else mode to conditions

addons/dialogic/Display/ChoiceButton.gd, addons/dialogic/Editor/Events/BranchEnd.gd, addons/dialogic/Other/DefaultDialogNode.tscn, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd
The default for the choice button (display node) is now -1 meaning the choices will be distributed to the members of the group in tree order.
If you didn't add events between a choice and it's end event, this resulted in incorrect loading of the timeline (it didn't detect the end branches as there was no change in indentation). This is fixed now and should also be fixed for conditions.
- the add elif and add else buttons are now hidden on choices
=> 2.0: Auto detect choice button order + empty choices fix

addons/dialogic/Nodes/Anima/animations/entrances_and_exits/slide_in_left.gd, addons/dialogic/Nodes/Anima/animations/entrances_and_exits/slide_in_right.gd
I wanted a simple character slide-in animation, but there were only back-in animations provided. I simply duplicated and modified back_in_right.gd and back_in_left.gd to remove the scaling so that I had simple slide-in animations.
=> 1.4: Added simple slide_in character entrance animations

addons/dialogic/Events/Choice/event.gd, addons/dialogic/Events/Condition/event.gd, addons/dialogic/Other/DialogicGameHandler.gd
Should fix #958
Adds a condition input to the choice event. UI is very bad but functionality is there. You can also choose, what to do if the condition isn't met (Default/Hide/Disable). Default is currently just the same as Hide, but I want to add a setting for this later.
In the text format you can write the conditions like this:
```
Emilio: Wow, some options are disabled!
- This is disabled [if false] [else disable]
- This might be disabled [if some_cool_condition] [else disabeld]
- This will be hidden [if false] [else hide]
- This is always visible
```
- moved the condition execution into a function of the dialogic_game_handler, because now multiple events (and the game_handler itself) use it.
=> 2.0 Add condition to choice

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn, addons/dialogic/Events/Change theme/event.gd, addons/dialogic/Events/Text/event.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/character.gd, characters/Jowan.dch
Should fix
- #937 
Adds 
- global portrait offset
- global portrait mirror
Implements
- character themes
- portrait search
- moved the "global" settings scale, offset and mirror one row below, so the editor is less cluttered
- added a current_state_info dictionary to the DialogicGameHandler. It's supposed to hold all info about the current state and make communication between events easier. For example it saves the current theme name and the current base_theme name (base_theme isn't affected by character themes and allows to go back after a character with a custom theme talked).
=> 2.0 Character Editor/Setting improvements 

addons/dialogic/Display/DialogText.gd, addons/dialogic/Display/DialogText.tscn, addons/dialogic/Events/Text/event.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/TestTimelineScene.gd
- fixes multiple items of (#966)
Added support for
- [pause=time] 
- [signal=arg]
- [speed=float]
- [portait=name]
Added support for
- [pick, a, word, or sentence]
- Modified testing scene (Play Timeline button)
-> will print on text signal command or signal event
-> will randomize() before starting timeline
- Made sure visual display elements only get updated if visible in tree. This is necessary because otherwise the hidden textboxes of other themes will cause text commands to be seemingly executed multiple times.
- Added text_signal signal to DialogicGameHandler, because I thought it would be nicer to have two different signals. 
- made sure the text event updates the current character in the current_state_info dictionary
=> 2.0 Text commands/modifiers

addons/dialogic/Display/DialogText.gd
- fixes #971
You can now use `\,` in `[Hello World, That's nice\, isn't it]` a word selector.
=> 2.0 Allow escaping \comma in word selector text modifier

addons/dialogic/Display/DialogText.gd, addons/dialogic/Other/DialogicGameHandler.gd
- still related to #971
You can now igore square opening brackets by having a backslash befor them. This will in turn ignore the content and closing bracket and leave it in.
- made sure the DIalogicGameHandler connects to the events using a OneShot flag, otherwise it would always complain when you reached an  event a second time (e.g. with a jump loop.
=> 2.0 Make sure text effect parser ignores`\[` 

addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd, addons/dialogic/Editor/Events/Templates/EventNode.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Events/Choice/event.gd, addons/dialogic/Events/Music/event.gd, addons/dialogic/Events/Sound/event.gd, addons/dialogic/Events/Text/event.gd, addons/dialogic/Resources/event.gd
- implementation of a fix for #955
Allows to add a condition (string) to header and body input fields of the dialog node. 
If the condition is true, they are shown, otherwise hidden.
They update on changes.
*Example Implementation*
Implemented on:
- Text event (portrait hidden if no character)
- Character event (Portrait & hidden if no character or mode == Leave)
- Sound & Music (Volume, Bus, Loop hidden if no path)
- Choice (ElseAction hidden if no condition)
=> 2.0 Allow dynamic input fields on dialog node

addons/dialogic/Nodes/DialogNode.gd
While the default for autofocus_choices was changed, the fallback was not, causing unexpected behavior when people toggled the option only once.
=> 1.4.x - Fixed autofocus_choices default

addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/DialogProxy.gd, addons/dialogic/Nodes/TextBubble.gd, addons/dialogic/Nodes/canvas_dialog_node.gd
Added new signal 'letter_displayed', which is emitted whenever a letter is written on the text bubble. This hooks into the existing 'letter_written' signal that plays the typing audio, and bubbles up further with the char that is written (including spaces).
This can be used to build a buffer and react to text as it displays on the screen, or time lip flaps, etc.
=> 1.4.x - Exposed Letter Written signal

addons/dialogic/Editor/Events/NoSkipEvent.tscn, addons/dialogic/Editor/Events/Parts/NoSkip/EventPart_NoSkip.gd, addons/dialogic/Editor/Events/Parts/NoSkip/NoSkipPart.tscn, addons/dialogic/Editor/Events/Parts/WaitSeconds/WaitSeconds.tscn, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Other/DialogicClass.gd, addons/dialogic/Other/DialogicUtil.gd
Added a no Skip event. This blocks default action input from working until an unchecked no skip event is reached. This is most useful for combining Dialogic with cut scenes and the [nw] command in order to avoid messed up timings.
Only advancement of dialog is skipped. Choices must still be made and will still accept mouse clicks/taps
=> 1.4.x - Added NoSkip Event and Auto Advance Mode

addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd, addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn, addons/dialogic/Editor/Events/Templates/EventNode.gd, addons/dialogic/Events/Character/AnimationsSettings.gd, addons/dialogic/Events/Character/AnimationsSettings.tscn, addons/dialogic/Events/Character/DefaultAnimations/bounce_in.gd, addons/dialogic/Events/Character/DefaultAnimations/bounce_out.gd, addons/dialogic/Events/Character/DefaultAnimations/fade_in_up.gd, addons/dialogic/Events/Character/DefaultAnimations/fade_out_down.gd, addons/dialogic/Events/Character/DefaultAnimations/heartbeat.gd, addons/dialogic/Events/Character/DefaultAnimations/instant_in_or_out.gd, addons/dialogic/Events/Character/DefaultAnimations/tada.gd, addons/dialogic/Events/Character/DialogicAnimationClass.gd, addons/dialogic/Events/Character/Subsystem_Portraits.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Events/Jump/event.gd, addons/dialogic/Events/Text/event.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/event.gd, timelines/testy.dtl
Animations are a script file that extends the new DialogicAnimation class.
There are currently X animations:
- fade_in_up
- fade_out_down
- bounce_in
- bounce_out
- instant_in_out
- tada
- heartbeat
These scripts have to have an `animate()` function. The class has a couple of variables that you can use, most importantly the `.node` which is a reference to the node that should be animated.
The animations should emit `finished_once` once finished. The animations above use the SceneTreeTweener for animating (except for the instant animation).
The `Character event` has a couple of more settings, that show under different circumstances:
- AnimationName (the path to the animation)
- AnimationLength
- AnimationRepeats
- AnimationWait
In the text version they are stored as an additional …
=> 2.0 Add Character Animation support

addons/dialogic/Editor/Events/EventNode/EventNode.gd, addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd, addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn, addons/dialogic/Editor/Events/styles/InputFieldsStyle.tres, addons/dialogic/Events/Character/PortraitSettings.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Events/Jump/event.gd, addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd, addons/dialogic/Events/Text/Settings_DialogText.gd, addons/dialogic/Events/Text/event.gd
You can now specify an icon for the resource picker.
You can do that also in the info dict in add_header_edit() or add_body_edit().
The keys are 'icon' for a texture or 'editor_icon' for an array like ['Animation', 'EditorIcons'] (because get_icon() is impossible in resources)
- icons have been added to the character, portrait, animation and timeline pickers.
If the search is empty or you click the new drop down button, the first 12 suggestions will show up. This is an arbitrary number that could be changed. If there are more then 12 suggestions a "..." will display at the bottom of the panel.
- many suggestion functions had to be updated to allow an empty search.
=> 2.0 Improve Resource Picker

addons/dialogic/Events/Call Node/event.gd
enable the inline option in the call_node event and add a code name (e.g. shake or flash or whatever).
use the [signal=code_name] and put the code name that you put in the call_node to call the method
one off means that you can only call the method once (useful if you want to free up the code name for something else)
disabling it means it will be active until the timeline ends (has to end, not be changed. although I might add an option about that)
=> add inline method calls

addons/dialogic/Editor/Common/Toolbar.gd, addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd, addons/dialogic/Resources/event.gd, addons/dialogic/Resources/timeline.gd
- Make sure timeline editor actions set unsaved
- Big TimelineEditor.gd cleanup
- Multiline events are now stored with the right index on ALL lines.
- Add Timeline and Add character button working again.
- event default end working properly (])
- timeline _get method added so the inspector can show the events again
=> Fixes and cleanup

addons/dialogic/Events/Voice/SerialAudioregion.tscn
this makes it compete with the audiobus field in Voice event, and saves a little bit of space in the UI.
=> Make serial audio region width-greedy

addons/dialogic/Editor/Events/EventNode/EventNode.gd, addons/dialogic/Editor/Events/Fields/ComplexPicker.gd, addons/dialogic/Editor/Events/Fields/ConditionPicker.gd, addons/dialogic/Editor/Events/Fields/ConditionPicker.tscn, addons/dialogic/Editor/Events/Fields/FilePicker.gd, addons/dialogic/Editor/Events/Fields/FilePicker.tscn, addons/dialogic/Editor/Events/Fields/Number.gd, addons/dialogic/Editor/Events/Fields/Number.tscn, addons/dialogic/Events/Background/event.gd, addons/dialogic/Events/Condition/event.gd, addons/dialogic/Events/Music/event.gd, addons/dialogic/Events/Sound/event.gd, addons/dialogic/Events/Variable/event.gd, addons/dialogic/Events/Voice/SerialAudioregion.gd, addons/dialogic/Events/Voice/event.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/event.gd
Adds a file picker. You can give it some placeholder text and a file filter (e.g. '*.png'). You can drag and drop files that fit that filter into the picker.
Pretty complex picker that allows to switch between "simple" editing and complex one. Simple editing provides three drop-downs.
doesn't use a popup anymore, instead it uses a ItemList node.
Not perfect yet, but a lot closer imo
=> Event UI picker updates

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn, addons/dialogic/Editor/Events/Fields/ComplexPicker.gd, addons/dialogic/Events/Character/Subsystem_Portraits.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd, addons/dialogic/Events/Text/CharacterEdit_TypingSounds.tscn, addons/dialogic/Events/Text/DialogicDisplay_TypeSounds.gd, addons/dialogic/Events/Text/event.gd, addons/dialogic/Resources/character.gd, characters/Emilio.dch, characters/Jowan.dch
- should fix #1038 
Adds a default_portrait property to the character resource, an editor field in the character editor and an option to the portrait picker on the Join event (the new default)
Adds a default mood setting to the TypeSound editor. This mood will be used if no custom mood is set for the current portrait.
=> Add default portrait and mood

addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/Settings/SettingsEditor.tscn
Sets the main popup size to match the size of the panel that the General tab was designed for. Also switches the order of the commands for the show_settings() command, which makes it actually change the size of the popup properly
=> 2.0 Settings Window Fix

addons/dialogic/Editor/Events/EventNode/EventNode.gd, addons/dialogic/Editor/Events/Fields/ComplexPicker.gd, addons/dialogic/Editor/Events/Fields/ConditionPicker.gd, addons/dialogic/Editor/Events/Fields/ConditionPicker.tscn, addons/dialogic/Editor/Events/Fields/OptionSelector.gd
=> QuickFix for ConditionPicker

addons/dialogic/Events/Character/event.gd
Fix for processing the shortcode on a Character event, loop is only supported for Update events but it was being checked for all types and throwing an error if missing
=> 2.0 Character Event Shortcode Fix

addons/dialogic/Editor/TimelineEditor/EventButton.gd
Just this file was throwing a script error because it happened to be still in 3.x export format and not 4.0
=> 2.0 Script Export

addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/timeline.gd
Fix for a weird locking issue I was running into stepping through to see why Dialogic.start_timeline() wasn't working by filename. Moves the file check to be before the resource creation, so it aborts if the filename is wrong, and asserts an error. Also, as I was stepping through one by one, as soon as it hit DialogicTimeline.new(), then the debugger got filled with infinite errors from the "for event_idx in _events.size():" line having size() fail because it was null, so checks to make sure it's not null before running that also
=> 2.0 Loading Issue

addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/TimelineResourceLoader.gd
Works for:
- Character portraits paths
- References to characters, timelines or strings that start with "res://" in all properties of events that are listed in the get_shortcode_parameters() method. This means that currently it does NOT work on the Text event, but that shouldn't be too much of a problem, because characters are only stored by reference anyways.
I would be very glad if someone could test this, because I have no idea if it will work in all edge-cases or have any negative performance costs. Didn't notice any so far, but my test project is relatively small in scope.
=> Add dependency updates when moving files in godot

addons/dialogic/Events/Character/Subsystem_Portraits.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Events/Choice/Subsystem_Choices.gd, addons/dialogic/Events/Converter/Settings_Converter.gd, addons/dialogic/Other/DefaultDialogNode.tscn, addons/dialogic/Other/DefaultPortrait.gd, addons/dialogic/Other/DefaultPortrait.tscn
Changes plain portraits into a scene, allowing them to be manipulated the same way as custom scenes by having all scenes uniform: 
- Adds the `DefaultPortrait` tscn and gd files, as the template for custom scenes. Dialogic will expect all portrait scenes to have the exported values and functions as listed in the top of this script as baseline for custom scene portraits to implement
- Updates `Subsystem_Portraits` and `Character\event' to use this new calling method
- Changes the position Update function. Was previously entered that -1 will be 'no change' for Update position, but the regex doesn't read this value properly, so it's been changed to 0. This shouldn't affect any other actual portrait positioning, as their indexes start from 1
Other changes:
- Updates the 1.x Converter to use …
=> 2.0 Change Basic Portraits Into Scene

addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd
Sometimes - not all the time - when starting Godot 4 current alpha, it seems to lose it's resource cache, and needs to reload everything. When this happens the Dialogic resource loader blocks Godot's UI from finishing indexing the rest of the project, and it sits there with an empty directory until it's done. 
Initially, before other speed improvement I had put in before, this was taking a very long time, upwards of 10 minutes for my VN project - which consists of 33 character files, 50 timeline files, and about 5000 events - as the baseline. My pverious changes brought it down to 2 minutes. This brings it down further, to under 20 seconds.  
This is implemented by just not actually doing the event processing at all, using the same changes that were happening on runtime as well. This …
=> 2.0 Resource Loader Further Speedups

addons/dialogic/Events/Character/DefaultAnimations/bounce_in.gd, addons/dialogic/Events/Character/DefaultAnimations/bounce_out.gd, addons/dialogic/Events/Character/DefaultAnimations/fade_in_up.gd, addons/dialogic/Events/Character/DefaultAnimations/fade_out_down.gd, addons/dialogic/Events/Character/DefaultAnimations/heartbeat.gd, addons/dialogic/Events/Character/DefaultAnimations/tada.gd, addons/dialogic/Events/Character/DialogicAnimationClass.gd, addons/dialogic/Events/Character/Subsystem_Portraits.gd, addons/dialogic/Events/Choice/Subsystem_Choices.gd, addons/dialogic/Events/Music/Subsystem_Audio.gd, addons/dialogic/Events/Text/DialogicDisplay_TypeSounds.gd, addons/dialogic/Events/Text/Display_DialogText.gd, addons/dialogic/Events/Text/Display_InputHandler.gd, addons/dialogic/Events/Text/Subsystem_Text.gd, addons/dialogic/Events/Text/event.gd, addons/dialogic/Events/Voice/Subsystem_Voice.gd, addons/dialogic/Events/Voice/event.gd, addons/dialogic/Other/DefaultPortrait.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/TestTimelineScene.gd, addons/dialogic/Other/TestTimelineScene.tscn
- supposed to fix #1075
This adds pause() and resume() methods to the DialogicGameHandler.
These will propagate down to the Subsystems and set the paused boolean of the DialogicGameHandler.
Pausing is implmented for:
- text/input/voice
- sound/music
- choices (won't trigger when paused)
Making the character animations pause did not yet work, because the portraits themselves are a bit broken a the moment. Also I haven't yet found a good way to get the tweens to pause them.
We can either wait, or fix that in a follow-up PR.
Also adds the ability to pause in the timeline test scene (Play Timeline) with KEY_P. 
Includes some changes to the Subsystem_Voice to have method names in snake_case.
=> Add pause() and resume() methods

addons/dialogic/Events/Text/Subsystem_Text.gd
- should fix #1143
This just parses variables before setting the name label text.
=> Allow variables in character display name.

addons/dialogic/Events/Character/Subsystem_Portraits.gd, addons/dialogic/Events/Character/event.gd, addons/dialogic/Other/DefaultPortrait.gd
Adds an extra_data shortcode parameter to Character events, to allow setting misc instructions on character Update events to give other directives to custom scene portraits, in a hopefully easier to use way than with a call_node to the custom portrait scene.  Since this isn't going to be used by most people, this is _not_ added to the Timeline Editor, so is only exposed by the Text Editor or editing the timelines outside of editor. 
Updates the PlainPortrait node with the functions for this parameter, and some brief documentation for how to use it when modifying PlainPortrait into a custom scene.
=> 2.0 Extra Data on Character Event

addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd, addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn, addons/dialogic/Nodes/DialogNode.gd
At the moment there is no possibility to customize the "focus" property of the choice buttons. This is important for situations where the game is not controlled mainly by mouse, which relies on the hover property. 
With this simple implementation and having the "Autofocus choice buttons" active in the settings it is possible to customize these buttons appearance upon getting focus, this feature is mainly targeted for controller and keyboard inputs.
=> - added the ability to customize the focus property of a choice button.

addons/dialogic/Events/Background/Subsystem_Backgrounds.gd, addons/dialogic/Events/Text/Display_DialogText.gd, addons/dialogic/Other/DialogicGameHandler.gd
- Fix for #1167
Will just reset the text of the dialog text in _ready()
- Fix for #1188 + Background Fade improvements
Fade now works on the first event. Also you can node implement _fade_in(*time) and _fade_out(*time) on your custom background scenes.
- Fix for #1166
Added a is_conected() check before connecting
Edit: accidently tagged a user named time.
=> Multiple bug fixes + Background Fade improvements

addons/dialogic/Events/Text/Subsystem_Text.gd
Adds a signal `speaking_character` to the Text subsystem. Sends the current display name of a Text event's character to the signal, or "(Nobody)" if there's not any character on that event. 
Purpose is to allow a game to listen for that event and do something with it, if they choose. For example, using multiple text boxes for different characters in a 2D/3D game that are positioned with that character, without any manipulation of themes in the timeline.
=> Speaking_Character Signal

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd, addons/dialogic/Editor/EditorView.gd, addons/dialogic/Editor/Settings/Settings_Translations.gd, addons/dialogic/Editor/VisualEditor/VisualEditor.gd, addons/dialogic/Events/Converter/Settings_Converter.gd, addons/dialogic/Events/Glossary/SettingsEditor/GlossaryEditor.gd, addons/dialogic/Events/Save/Subsystem_Save.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/CharacterResourceSaver.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd
There are many things to replace, so it might need thorough testing.
=> Started working on the beta 2 update for Dialogic 2

addons/dialogic/Resources/CharacterResourceSaver.gd
There were two issues with character saving:
* There was a check to see if the file exists first, resulting in new files never being created
* The files were opened in READ mode instead of WRITE
=> Fix for allowing character resources to be saved.

addons/dialogic/Editor/Events/EventNode/EventNode.gd, addons/dialogic/Editor/Events/Fields/ConditionPicker.gd, addons/dialogic/Editor/VisualEditor/VisualEditor.gd, addons/dialogic/Events/Condition/Condition_End.gd
Conditions with strings should not fail anymore. They require to be put in quotationmarks though which the visual editor will do if you entered a string.
Also the AddElif and AddElse buttons work again. Also they now hide if the event is of type ELSE and the Add Else button is hidden if the next event is a ELIF or ELSE event. I hope these checks are not to intensive, as they have to be done everytime indentation is done.
- should fix #1258 and #1178
=> Fixes for Conditions

addons/dialogic/Events/Jump/event.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/timeline.gd
Adds a stack for timeline jumping, and option on the Jump event to return to the timeline after completing the timeline jumped to. Once reaching the end of a timeline, it will check the stack, and take the top one off if there's still more on the stack, and only call end_timeline() once the stack is empty
For example, take the following three timelines:
Running the timeline from sub1.dtl will then have the timleine events play in this order:
base 1
base 2
sub 1
sub 2
sub sub 1
sub sub 2
sub sub 3
sub sub 4
sub 3
sub 4
base 3
base 4
=> Timeline Jump Stack

addons/dialogic/Events/Text/Subsystem_Text.gd
Converting an array to a string now adds " to all strings, so I had to remove them from the regex.
- Should fix #1276
=> Fix autocoloring

addons/dialogic/Nodes/DialogNode.gd, addons/dialogic/Nodes/DialogProxy.gd, addons/dialogic/Nodes/canvas_dialog_node.gd
**timeline_end** and **timeline_start** now appropriately recognize when a timeline change event occurs and update their output appropriately.
Added **timeline_changed** signal. 
**timeline_changed** fires when a Change Timeline Event occurs, and returns the old timeline and the new timeline in that order
=> Fixes for Timeline End and Timeline Start

addons/dialogic/Other/DialogicResources.gd
commit = 56ca167
**Dialogic 1.4.5+**
Additional functions added to get_save_definitions()
Helps games already published to be able to expand dialogic vn game by:
Adding new default variables, and deleting depreciated default variables (which help function's loop speed).
Addresses issue #1278, and would close it.
=> get_saved_definitions() new loop function to add / delete default definitions

addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Events/Label/event.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/CharacterResourceSaver.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/TimelineResourceSaver.gd, addons/dialogic/Resources/event.gd
The timeline saving logic has been simplified.
The TimelineResourceSaver now accepts both Timelines with text arrays as well as event arrays. If an event_array is present, it will convert it to text.
The visual timeline editor saves with a event array, while the text editor saves with a text array.
The number of empty lines is now stored in the next event (in the events.empty_lines_above property). This allows to save them even when events are resources.
The name field of the label event wasn't working
=> Timeline saving simplification, emty_line preserving, label event fix

addons/dialogic/Editor/CharacterEditor/character_editor.gd
To address SCRIPT ERROR: Invalid call. Nonexistent function 'is_tool' in base 'Nil'. when using a custom scene that doesn't have a script as a portrait
to address issue https://github.com/coppolaemilio/dialogic/issues/1331
=> Check for script before checking is_tool

addons/dialogic/Example Assets/History/HistoryRow.gd, addons/dialogic/Nodes/History.gd
Since resolving it in History.gd will disable the speed effect. I am resolving it in the HistoryRow.gd instead.
The speed tag is removed using Regex. It will cater below situation:
[speed=1234567890]
[speed=23 ]
[ speed=23]
[speed = 23]
[ speed = 23 ]
But not
[custom_effect speed=23 span=23]
Just in case anyone wants to use speed as an argument for a custom RichTextEffect.
=> Fixed Speed tag resolve in HistoryRow

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/CharacterEditor/character_editor.tscn, addons/dialogic/Editor/CharacterEditor/character_editor_portrait_settings_tab.gd, addons/dialogic/Editor/CharacterEditor/character_editor_portrait_tree.gd, addons/dialogic/Editor/CharacterEditor/character_editor_ptab_exports.gd, addons/dialogic/Editor/CharacterEditor/character_editor_ptab_image.gd, addons/dialogic/Editor/CharacterEditor/character_editor_tab_general.gd, addons/dialogic/Editor/CharacterEditor/character_editor_tab_general.tscn, addons/dialogic/Events/Character/default_portrait.gd, addons/dialogic/Events/Character/default_portrait.tscn, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/Text/character_settings/ui_mood_item.tscn, addons/dialogic/Events/Text/node_type_sound.gd, addons/dialogic/plugin.gd
- #1047, #666
The portrait list now allows to add groups. These are not actually saved. If a portrait is in a group it will be saved as it's full path (with / e.g.: "Group/Subgroup/Portrait").
You can now also drag and drop to reorder/reparent portrait items.
- #820
Custom portrait scenes now have a Export tab in the portrait settings section. If the scenes script has some exported variables, they will be listed there. 
For scenes that are in @tool mode, updates can be shown in editor (even with transitions if _should_do_portrait_update() returns true).
These "export_overrides" are saved in the portrait data and applied on change_portrait().
- Fix some preview updating bugs #1192, #1361, #1360, #1363
--> Note: Most of these were fixed by making the character editor autosave again, as that …
=> Character Editor Update

addons/dialogic/Events/Save/event_save.gd, addons/dialogic/Events/Save/subsystem_save.gd, addons/dialogic/Events/Text/subsystem_text.gd
The save event will now handle an empty name differently. If slot_name is empty it will attempt to save to the latest loaded slot, otherwise use the default slot (from the dialogic settings).
- added saved signal
- refactored/fixed thumbnail making.
- added lot's of documentation
Importrant: All slot methods will now use the default slot if slot_name is empty.
Only load() and save() will update the latest_slot. This means calling reset(), save_file(), load_file() will all NOT change the "current slot".
- the latest slot is now saved in a custom global_info file. Using the project settings turned out to be SUPER annoying, because godot would start to complain about the project file having changed. 
- made sure attempting to load from non-existent slot would produce error, but not failure
- …
=> Save system updates

addons/dialogic/Editor/Events/Fields/FilePicker.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Example Assets/default_event.gd
Fix a few SCRIPT ERRORs at startup:
- Don't return value from create_drag_and_drop_event, which returns void
- Fix Category enum value MAIN -> Main
- Update set_drag_forwarding and associated signatures: There were some changes to set_drag_forwarding in Godot 4:
- `Control.set_drag_forwarding` takes three callables instead of an object
- `_can_drop_data_fw`, `_drop_data_fw` don't have a `from_control` argument anymore
=> Fix a few editor startup errors

addons/dialogic/Events/Character/index.gd, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/Text/event_text.gd, addons/dialogic/Events/Text/index.gd, addons/dialogic/Events/Text/node_dialog_text.gd, addons/dialogic/Events/Text/subsystem_text.gd, addons/dialogic/Other/index_class.gd
Removes the text effect and modifier logic from the DialogText node.
The index.gd file can now register text effects and modifiers.
These are effectively just methods. The text subsystem collects them and applies/reads them to/from the text before sending it to the DialogText node. Then the DialogText node calls execute_effects on every letter advance. 
Text modifiers are also methods, these are only called once before the text is shown.
The text effect methods have access to the calling dialog_text node, the skipping boolean and the argument string. 
All effects/modifiers have been moved to the text subsystem except portrait which is now part of the portrait subsystem.
Additionally the syntax for random selection has been changed from [option1, option2] to [option1/option2].
This PR …
=> Make text effects and modifiers modular

addons/dialogic/Editor/Settings/settings_general.gd, addons/dialogic/Editor/Settings/settings_layouts.gd, addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
In https://github.com/coppolaemilio/dialogic/pull/1421 `DialogicDefaultLayout` (formerly `DialogicDefaultScene`) was moved and renamed, however paths pointing to its location were not updated, because GDScript is a very good language and refactoring code written in it is always a pleasure.
There are some occasional formatting fixes to dilute the atmosphere of inevitable hardcoded doom.
=> Fix default layout path

addons/dialogic/Events/Character/event_character.gd
=> Hide portrait picker if character has none or only one portrait

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Events/Variable/event_variable.gd
- also simplifies the event detection in the visual timeline editor (inspired by nathanhoad, thanks!)
- makes space after VAR optional, to allow copying of set variable events.
Fixes #1444
=> Fix for copying text and character event

addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/Text/node_dialog_text.gd, addons/dialogic/Events/Text/subsystem_text.gd, addons/dialogic/Other/DialogicGameHandler.gd
Revealing new letters is now done in _process() instead of with a timer to allow revealing multiple characters in the same frame. 
- also removes leftover character_positions stuff in get_full_state()
- also fixes static typing in portrait subsystem get_joined_characters()
- add [br] syntax highlighting
- fixes #1412
=> Change how text speed works (to allow faster text speeds)

addons/dialogic/Editor/Common/sidebar.gd
=> Fix resources not getting added to sidebar

addons/dialogic/Events/Glossary/event_glossary.gd
This PR sets `event_category` in `DialogicGlossaryEvent` to `Other` because the previous value, `AudioVisual`, is not found in `DialogicEvent.Category`.
I originally presumed `Other` to be the category, but it could be `Audio` instead. Let me know the intended category, and I'll make a new PR branch.
=> Changed Glossary Category

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/dialogic_editor.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/DefaultLayouts/HideWithChild.gd, addons/dialogic/Events/Glossary/event_glossary.gd, addons/dialogic/Events/Text/subsystem_text.gd, addons/dialogic/Events/Variable/variables_editor/variables_editor.gd, addons/dialogic/Other/DialogicUtil.gd
Make sure variable editor saves when the editor saves not only when you switch editor. This resulted in a rename of _resource_saved() to just _saved() in the DialogicEditor class and thus the other dialogic Editors.
Added static tpying in a couple of places.
Added handy methods to the portrait subsystem. Also changed what is given with the Dialogic.Text.speaking_character signal (now the character resource).
=> Various smaller fixes

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/dialogic_editor.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/DefaultLayouts/HideWithChild.gd, addons/dialogic/Events/Glossary/event_glossary.gd, addons/dialogic/Events/Text/subsystem_text.gd, addons/dialogic/Events/Variable/event_variable.gd, addons/dialogic/Events/Variable/variables_editor/variables_editor.gd, addons/dialogic/Other/DialogicUtil.gd
Fix for string values not being assigned correctly in Set variable event.
- fixes #1499
=> Fix for #1499

addons/dialogic/Events/Audio/subsystem_audio.gd, addons/dialogic/Events/Background/subsystem_backgrounds.gd, addons/dialogic/Events/Character/subsystem_portraits.gd, addons/dialogic/Events/Choice/subsystem_choices.gd, addons/dialogic/Events/Jump/event_jump.gd, addons/dialogic/Events/Jump/subsystem_jump.gd, addons/dialogic/Events/Style/subsystem_styles.gd, addons/dialogic/Events/Text/default_input_handler.gd, addons/dialogic/Events/Text/subsystem_text.gd, addons/dialogic/Events/TextInput/subsystem_text_input.gd, addons/dialogic/Events/Variable/event_variable.gd, addons/dialogic/Events/Variable/subsystem_variables.gd, addons/dialogic/Events/Voice/subsystem_voice.gd, addons/dialogic/Other/DialogicGameHandler.gd
Added many signals to all the subsystems. 
Most of these just give one info dictionary argument. While this is initally not as nice as giving named arguments, it means we can way more easily provide mode information in the future without breaking any code.
Added signals:
- Voice: voiceline_started, voiceline_finished, voiceline_stopped
- Variable: variable_changed, variable_was_set
- TextInput: input_confirmed, input_shown
- Text: text_finished, speaker_updated, textbox_visibility_changed
- Style: style_changed
- Jump: switched_timeline, jumped_to_label, returned_from_jump
- Choices: choice_selected, choices_shown
- Portraits: character_joined, character_left, character_portrait_changed, character_moved, position_changed
- Background: background_changed
- Audio: music_started, …
=> Big signal update

addons/dialogic/Events/Text/node_dialog_text.gd
After a pause the text would continue to reveal even if it was skipped during the pause. A new check checks for this ;).
=> Fix bug where skipping during [pause] doesn't work correctly

addons/dialogic/Events/Text/subsystem_text.gd
There are a few places where we do a `update_name_label(null)`, which makes `character.resource_path` throw an invalid index error. This commit fixes this bug; also a fixes a related bug in the same function where it is possible to access
`dialogic.current_state_info['character']` before it is defined.
=> add null check to text update_name_label

addons/dialogic/Events/Converter/settings_converter.gd
Otherwise, the value would have been taken null and the code won't progress further.
This is a fix to the timeline conversion.
=> Check if Keys are Avaiable

addons/dialogic/Events/Converter/settings_converter.gd
This prevent "directory" from being set to null upon calling "DirAccess.make_dir_absolute(dir)".
Also, make "refresh()" to be called on itself rather than its parent.
=> Make Sub Directories if Not Already Existed

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/CharacterEditor/character_editor.tscn, addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
Makes it so when no character is opened you don't see the empty character editor and instead a prompt to create or open a character.
=> Add empty mode for character editor

addons/dialogic/Events/Text/index.gd, addons/dialogic/Events/Text/settings_text.gd, addons/dialogic/Events/Text/subsystem_text.gd
Adds autopausing for certain letters. The sets of letters can be changed in the DialogText settings page.
The autopausing is done as a modifier that adds [pause] effects after these letters. A regex is used so letters inside of [brackets] or {brackets} are not altered. This is mainly important for the dot (.).
=> Add autopausing-capability

addons/dialogic/Events/Text/node_next_indicator.gd, addons/dialogic/Events/Text/settings_text.gd, addons/dialogic/Events/Text/settings_text.tscn, addons/dialogic/Events/Text/subsystem_text.gd
There was a confusion with the autoadvance setting being named autocontinue in some places and thus not properly working. 
It's now ALWAYS named autoadvance.
=> Make sure autoadvance setting works

addons/dialogic/Events/Background/event_background.gd, addons/dialogic/Events/Variable/event_variable.gd, addons/dialogic/Events/Variable/subsystem_variables.gd
- fix for #1521
-> For some reason first level variables wheren't set if the existing value wasn't a string. I cannot remember any good reason for this, so I removed it. Hope this doesn' result in problems again.
- fix for #1520
-> Changed placeholder text of the set variable event
- work on #1522
-> Made sure you cannot select a scene in the image picker of tha background event, also fixed not capitalized texts
=> Fix event issues found by emilio

addons/dialogic/Events/Character/subsystem_portraits.gd
Fix for #1474, by making sure the game doesn't crash, only prints an error when an invalid position index is given.
=> Fix for #1474

addons/dialogic/Events/Converter/settings_converter.gd
Converter has minor errors that keep it from running.  This will at least get the converter to run again. 
*Caveat
if you had variables as names in Dialogic 1.x,
there's a conflict with the auto color: subsystem_text.gd 
...
**for result in color_regex.search_all(text):**
...
Workaround if you want to keep variables as names...
1. go to : Project Settings...
2. turn on : Advanced Settings...
3. scroll down to : Dialogic/Text
4. turn off : Autocolor Names
5. lastly, back in character profile:  use {} instead of [] in name
Else: currently, you have to convert your variable names into manually typed static names.
=> Dialogic 1.x Converter minor fixes

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
When opening a visual timeline while another one is still loading (fairly common with longer timelines) the last batch would always still be added to the newly opened timeline. A new check now waits for the last batch of the previous timeline before clearing the timeline.
=> Add safety check when interrupt-loading a timeline

addons/dialogic/Editor/Settings/settings_editor.tscn, addons/dialogic/Editor/Settings/settings_general.gd, addons/dialogic/Editor/Settings/settings_modules.gd, addons/dialogic/Editor/Settings/settings_modules.tscn, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Events/Audio/event_music.gd, addons/dialogic/Events/Audio/event_sound.gd, addons/dialogic/Events/Character/event_character.gd, addons/dialogic/Events/Text/event_text.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/event.gd
There is a new settings tab that allows managing all the modules and extensions. It has a fully functional tree list of all the modules and their parts.
There is a editor for the event defaults. If changed these will be stored in a event default override dictionary. From there they are automatically set in each event before the actual event is loaded. Shortcode events also take these defaults into account for saving (won't add a value if it's the custom default).
I had to make sure these custom defaults are also applied to new events in the visual editor (as they are not acutally "loaded" there if new).
You can also specify default values for the text event (character and portrait settings). 
For this to be fully functional, I had to add some syntax flavors. 
With no default character and …
=> Add modules manager and first default override ability

addons/dialogic/Resources/event.gd
When shortcodes started similar the event would falsy claim to be that event as it didn't check for a non word character. It now checks if after the shortcode a space or a closing bracket ] follows.
=> Fix for event detection failing

addons/dialogic/Events/Text/event_text.gd
When having set a character for the text event (in visual editor), setting it to No One again didn't work, because character_from_directory didn't deal with an empty string correctly.
=> Fix No One setting being ignored in text event

addons/dialogic/Modules/Text/settings_text.gd
Hey, this is my first PR so I'm a little bit lost, I hope everything it's okay, tell me if I need to change anything :)
I felt fairly confident I could help with this issue in particular. But as I was approaching it I thought it could've been done in different ways:
I went with the 'D' case, with the 'B' one being the second I like the most. I feel like if the remove button is to the right of the time input I would delete the auto-pause set trying to change the value with the arrows.
Also while addressing this I realized 2 things:
- When you add a lot of auto-pauses the UI breaks, I don't think anyone is gonna need that much but maybe is worth to know: 
- It only saves the auto-pauses when swapping the main tabs:
I'm not sure if that's already known but I wanted to say them in case they …
=> Addressing Issue #1552 remove auto-pauses

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
It DOES:
- make sure timelines are never saved empty when they shouldn't be
- save timeline when clicking the X button to close godot
This does NOT fix
- unsaved changes getting lost when using `quit to project list` or `reload current project`
=> This makes timeline erasing less likely

addons/dialogic/Modules/Background/default_background.tscn, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn
- Safety check in `remove_portrait()`. This makes sure dialogic doesn't try to remove outdated nodes based on "saved" references (which are NOT nodes anymore at that point)
- Make backgrounds click-blocking (clicking through backgrounds seemed very weird)
- Make sure glossary works (make input-blocking control node pass through)
=> Multiple fixes (portraits, backgrounds, glossary)

addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/DialogicUtil.gd
The single-instance argument was removed as multiple instances have little to no use. 
Instead the ability to specify a custom scene and custom export overrides was added to the add_layout_node() method. This allows using different themes along with the .start() method (by calling add_layout_node() before).
Also added helpful comments
=> Improve start method

addons/dialogic/Editor/Settings/settings_general.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Settings/event_setting.gd, addons/dialogic/Modules/Settings/icon.svg, addons/dialogic/Modules/Settings/icon.svg.import, addons/dialogic/Modules/Settings/index.gd, addons/dialogic/Modules/Settings/subsystem_settings.gd, addons/dialogic/Modules/Text/character_settings/ui_mood_item.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/node_dialog_text.gd, addons/dialogic/Modules/Text/settings_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/Variable/event_variable.gd, addons/dialogic/Resources/event.gd, addons/dialogic/plugin.gd
Adds a new settings subsystem and event.
The settings subsystem will manage any settings stored in ProjectSettings dialogic/settings category.
The pros:
- settings are persistent and global
- settings can be accessed from code easily
- settings can be accessed from settings event
Can change or reset settings values. Has a custom syntax. Has syntax highlighting.
The only setting to utilize this right now is the text_speed setting.
- add placeholder text to set variable variable picker
- moves PortraitMode enum from character event to character subsystem (where it is used)
- fixes generated event script from Module creation
- makes the default_input_event mouse action "All devices"
=> Add persistent settings and Settings subsystem/event

addons/dialogic/Editor/Settings/settings_modules.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Modules/Choice/settings_choices.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd, addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn, addons/dialogic/Modules/Text/default_input_handler.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/node_dialog_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/Wait/event_wait.gd, addons/dialogic/Modules/WaitInput/event_wait_input.gd
This is an unfortunate mess. I've been working on the example projects and making changes as needed along the way. This is the result of that.
Here is a list of the most prominent changes:
- you can now choose how/when choices are revealed. either
- instantly when the text finished (default, because previous behaviour)
- after a certain time (very useful if text speed is instant (0))
- after another input
- after an input OR a certain time
- The input handler now emits a dialogic_action signal that can be listend to
- The input handler reference in the Text subsystem is now named input_handler (previously input_handler_node)
The DialogText node now has three new settings: `enabled`, `hide_when_empty` and `textbox_root`. 
- if enabled is false, this node will ignore calls to …
=> Multiple fixes (all over the place)

addons/dialogic/Modules/Glossary/subsystem_glossary.gd
=> Use ResourceLoader.exists() for glossary check

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Fixes the issue with #1609 in a better way, by making sure we only check if event is pressed, if event has a pressed property (thus fixing it if someone has connected in gamepad or even possible issues if someone has connected in a midi input device)
=> Fixed input bugs with event pressed and gamepad (#1609)

addons/dialogic/Other/DialogicUtil.gd
The property is supposed to be `dialogic/extensions_folder`, plural and without the trailing `/`. This broke custom extensions folders.
=> Fix extensions_folder typo

addons/dialogic/Editor/CharacterEditor/char_edit_section_portraits.gd, addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn, addons/dialogic/Modules/Text/node_dialog_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/TextInput/event_text_input.gd, addons/dialogic/Modules/Voice/event_voice.gd, addons/dialogic/Other/DialogicGameHandler.gd
- fixes #1620
- fixes #1619
- fixes #1610
- fixes #1611
Also fixes multiple other issues:
- no layout mode still added layout node
- default layout position 0 was misplaced and had a wrong stretch mode
=> Multiple bug fixes

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
- fix for #1627
- however this is not fixed by selecting the event that was right clicked. Actually move up and move down already were affecting the right clicked event correctly (even unselected). This has just been done for deletion as well.
- adds undo/redo support to the right click actions
=> Fix event deletion in right-click-menu and add Undo support to actions

addons/dialogic/Modules/Variable/subsystem_variables.gd
The VAR.reset() method allows to reset all or a specific variable.
The VAR.has() method allows to check if a given variable path exists.
=> Fix variable reset and add reset and has method

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Other/DialogicGameHandler.gd
As per the `Object` docs, providing a default value of `null` to the `get_meta` call doesn't silence the error in the event that the metadata key doesn't exist. We have a few instances of this pattern throughout the codebase, which were producing unintended error messages under certain circumstances.
This commit replaces them with explicit `has_meta` checks, where appropriate. In situations where the null value should be an error (typically because it was previously checked) I removed the default argument, to avoid confusion (the behavior is the same).
Also did some boy scout rule cleanup of trailing whitespace and refactored some confusing branch logic in `DialogicGameHandler.gd`.
=> Silence error on get_meta(..., null)

addons/dialogic/Modules/Text/default_input_handler.gd, addons/dialogic/Modules/Text/settings_text.gd, addons/dialogic/Modules/Text/settings_text.tscn
Adds a timer to the input handler that discards inputs every x seconds, which effectively delays the skipping of events and animations.
Adds config to configure that x delay. Delay is optional, 0.0 results in the default behavior.
Fixes problems with dialogic eating inputs or processing them twice sometimes, leading to accidently skipped events, especially on web builds. (Which I was too lazy to open an issue for)
Enables users to set a general global delay for skipping events.
Tested with some styles and configurations, but I'm not proficient with the dialogic structure.
=> Add skip delay

addons/dialogic/Modules/Text/default_input_handler.gd, addons/dialogic/Modules/Text/node_dialog_text.gd
Skip delay of 0 wasn't working because timers don't accept a wait time of 0.
I also converted the skip_delay_timer to a more general input_block_timer. 
I also added a 0.1 second input block when text finishes naturally. This is useful as often (for short texts) you think you want to reveal the full text, but then when you click it already finished revealing and you go to the next event. Hopefully this helps prevent this, by giving a short moment to realize the text finished (as indicated by the next inidicator).
=> Fix skip delay of 0 and add short input block after natural text finish

addons/dialogic/Editor/HomePage/home_page.gd, addons/dialogic/Editor/HomePage/tips.txt, addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Modules/Text/settings_text.tscn, addons/dialogic/Modules/Text/subsystem_text.gd
Random selection is now indicated like this <OptionA/OptionB>.
It is also highlighted in the text editor.
=> Fix for #1635 and #1593 and random selection highlighting

addons/dialogic/Editor/Common/reference_manager.gd
A weird bug was happening with indentation that was making the reference_manager script to not load. I also fixed a typo I found there.
=> Small broken reference fix

addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/Events/Fields/MultilineText.gd, addons/dialogic/Editor/Events/Fields/MultilineText.tscn, addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/directory_holder.gd, addons/dialogic/Modules/Jump/event_jump.gd, addons/dialogic/Modules/Jump/event_label.gd, addons/dialogic/Modules/Jump/event_return.gd, addons/dialogic/Modules/Jump/index.gd, addons/dialogic/Modules/Jump/subsystem_jump.gd, addons/dialogic/Resources/timeline.gd
This changes the syntax for jump & label and introduces the new return event.
New syntax:
```
label MyLabel
jump MyLabel
jump SomeTimeline/ 
jump SomeTimeline/SomeLabel
return
```
The best thing is probably that it brings autocompletion back for labels... YES!
=> Rework jump+label+return system

addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Character/index.gd, addons/dialogic/Modules/Character/settings_portraits.gd, addons/dialogic/Modules/Character/settings_portraits.tscn, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Other/index_class.gd
This removes the "Custom Animations Folder" setting and will instead allow animations to be added by modules. This should allow animation packs being distributed the same way as other modules.
=> Make custom animations part of the module system

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/Events/Fields/ComplexPicker.gd, addons/dialogic/Editor/Settings/settings_translation.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Text/event_text.gd
Character
- Adds Ctrl+E for adding a character event
- Adds Ctrl+Shift+E for adding a character update event
- Adds Ctrl+Alt+E for adding a character leave event
Text
- Adds Ctrl+Shift+T for adding a text event with previous character
- Adds Ctrl+Alt+T for adding a text event with the previous previous character
Other
- Adds Ctrl+J for a jump event
- Adds Ctrl+L for a label event
Adding
- Adds Ctrl+1 for adding a new timeline
- Adds Ctrl+2 for adding a new character
=> Add shortcuts

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Hotkeys: Added ALT == Option key compatibility for mac
=> Hotkeys - ALT == Option key 4 mac added

addons/dialogic/Modules/Variable/variables_editor/variable_field.gd, addons/dialogic/Modules/Variable/variables_editor/variable_group.gd
Now variable groups and fields autocorrect hyphens in it's name by changing them to underscores as they did with spaces.
=> Fixed variables hyphen symbol issue #1634

addons/dialogic/Modules/DefaultStyles/Default/animations.gd
Fixed an error in `animation.gd`.
* If `animation_finished` signal is already connected to `Dialogic.Animation.animation_finished`, it will cause this error  [@GlobalScope.ERR_INVALID_PARAMETER](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-constant-err-invalid-parameter)
* According to [Signal](https://docs.godotengine.org/en/stable/classes/class_signal.html#class-signal-method-connect) docs, use [is_connected](https://docs.godotengine.org/en/stable/classes/class_signal.html#class-signal-method-is-connected) first to check for existing connections.
=> Fixed ERR_INVALID_PARAMETER in animation.gd

addons/dialogic/Editor/CharacterEditor/char_edit_section_general.tscn, addons/dialogic/Editor/CharacterEditor/character_editor.gd
Also removes constant saving of character resources.
=> Remove fit_content_height from Description TextEdit to prevent crash

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Modules/Character/event_position.gd, addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn, addons/dialogic/Modules/DefaultLayouts/HideWithChild.gd, addons/dialogic/Modules/DefaultLayouts/TextBubble/TextBubble.tscn, addons/dialogic/Modules/History/event_history.gd, addons/dialogic/Modules/Settings/event_setting.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/node_name_label.gd, addons/dialogic/Modules/Variable/event_variable.gd, addons/dialogic/Resources/event.gd
- multiple fixes for visual editor lines not updating properly
- add support for nicely named enums (#1222)
- add name_label_root setting (#1549)
- change VAR syntax to set (#1187)
- make sure text events won't break if started with syntax words
=> Many fixes

addons/dialogic/Modules/LayoutEditor/Components/StyleItem.gd, addons/dialogic/Modules/Text/default_input_handler.gd
this somewhat fixes a particular bug I've experienced in text handling, in which as far as i can tell:
- the user triggers `dialogic_default_action` on the same frame they also trigger another input action (say, moving the mouse)
- `_input` is called for the `dialog_default_action`, `dialogic_default_action` has been pressed this frame, so the coroutine to advance text (`handle_event`) starts
- `_input` is called for the other action, `dialogic_default_action` has been pressed this frame, so the coroutine to advance text starts again
- the coroutines resolve, text is advanced twice, and a line gets skipped
i believe this PR fixes the input situation, but the race condition still probably exists. i don't understand how godot godot coroutines work well enough to tell if it's actually an …
=> Fix input event handling

addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/event.gd
This also somewhat adresses discussion #1637
=> Fixes for #1712 and #1707

addons/dialogic/Modules/Core/subsystem_expression.gd
Found by (@)siberius on discord. A simple regex failure.
=> Fix regex for expressions with two variables

addons/dialogic/Editor/Settings/settings_general.gd, addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Resources/character.gd
- make runtime characters possible by removing need for resource_path
- move `guess_animation_file` to DialogicUtil
- remove need for scale property on portrait info (fixed get() statement)
- add a get_portrait_container(idx) method to portrait subsystem
Also
- fix bad reference to visual editor in settings general
=> Small fixes / improvements to portrait system

addons/dialogic/Modules/Jump/event_jump.gd
Previously jumps to labels with spaces in them would just do nothing.
=> Allow spaces in jump's Label and Timeline regex

addons/dialogic/Resources/CharacterResourceLoader.gd
If using FileAccess.file_exists(), I can't load character portrait in HTML game. This is the same issue in #90 and fixed in PR #91. It seem like the fix not carried over to Dialogic 2.0.
=> Change file exists method for CharacterResource

addons/dialogic/Modules/Settings/subsystem_settings.gd
=> Make sure connect_to_change is only called on actual changes

addons/dialogic/Editor/Events/Fields/MultilineText.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
It's the same script but with a flag switched.
- fixes #1758
=> Add dedicated text-event syntax highlighter

addons/dialogic/Other/DialogicResources.gd
=> Fix Android directory errors

addons/dialogic/Editor/HomePage/home_page.tscn
The home page uses "let's" instead of "lets" and it's bugging me.
=> Fixed typo on home page

addons/dialogic/Editor/Events/Fields/MultilineText.gd, addons/dialogic/Editor/Events/Fields/MultilineText.tscn
This is a temporary fix for https://github.com/godotengine/godot/issues/80546 which crashes godot when the visual editor has wrapping texts and gets resized.
=> Add custom MultilineText sizing logic to prevent crash

addons/dialogic/Modules/Text/node_next_indicator.gd
Resolves https://github.com/coppolaemilio/dialogic/issues/1809
When a new animation started, it would take the values left behind by the previous tween. By keeping a reference to the current animation tween we can ask it to clean up first before having a new tween take over.
=> Fix next indicator slipping off screen

addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/Dialogic_Subsystem.gd
* this "install" method can be safely used by subsystems which rely on other subsystems
* fixes #1819 which was caused by a subsystem fetching another subsytem not yet in the tree (introduced by #1718)
Since the subsystems are loaded by parsing the directory, I assume the order might vary by OS (I'm on Linux and could reproduce #1819).
=> Add a separate install step after adding all subsystems

addons/dialogic/Modules/Variable/subsystem_variables.gd
This means there is no need to access the variable dictionary directly.
```
Dialogic.VAR.my_folder.variables() # returns an array of the variables
Dialogic.VAR.my_folder.variables(true) # returns an array of the variables as absolute (e.g. my_folder.my_variable)
Dialogic.VAR.my_folder.variables().pick_random() # returns a random variable in this folder
Dialogic.VAR.locations.folders().pick_random().variables().pick_random() # picks a random location in a random location folder
```
These methods do also work on the root Dialogic.VAR  level.
Also adds folder.has() method so you can check 
```
Dialogic.VAR.my_folder.has("Variable")
```
(as you could on the root level already)
I think this is a cool change allowing to get more information from the variables without accessing …
=> Allow listing variables and folders inside of variable folders

addons/dialogic/Editor/Settings/settings_translation.gd
This PR fixes two bugs when updating CSV using the Translation feature.
- Adding a new translatable event breaks CSV file, if there are more than 2 locale keys.
- Updating the CSVs closed the currently opened timeline.
When a new line of text gets added to the CSV, eg. by adding a Text Event, it did not add trailing commas for each available locale.
Additionally, updating CSVs closed the current timeline node, but did not re-open it.
We count the number of locale entries and count each entry per CSV row.
For every missing entry, we add trailing commas.
We also save the resource at the beginning of the method and once finished, silently open it again.
Changes comments and their positioning, adds a newlines were it helps readability.
In the future, this code section will require a full …
=> Fix CSV breaking when new rows get added.

addons/dialogic/Editor/Settings/settings_general.gd
=> Use `toggled` signal for toggling `phyics_process`

addons/dialogic/Modules/Choice/node_choice_button.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd
Using a key input crashes the choice selection using hotkeys.
Use `keycode` instead of `scancode`.
This PR adds an export to the Choice button class, allowing developers to define customisable inputs. This has been advertised by the settings page for Choices, but was not doable.
The variable for this is a typed array, allowing developers to provide multiple input choices, in case of different platforms.
This closes: #1870
=> Fix Choice Selection via Key Inputs

addons/dialogic/Modules/Character/subsystem_portraits.gd
When the custom defined portrait path fails to load, the code still tries to interact with the null instance, since it only handled the case where the path was Empty, but not when simply incorrect/broken path.
Instead of `scene_path.is_empty()`, we could also use `FileAccess.file_exists(scene_path)`, but figured I'd avoid the double file access command. But maybe it would be better, to avoid the load exception, I'm not sure.
=> Handle incorrect Portrait Scene path case

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/Common/update_install_window.tscn, addons/dialogic/Editor/Events/Fields/ComplexPicker.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/dialogic_editor.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Modules/Text/subsystem_text.gd
- fixes [pause] effect
- fixes #1807
=> Multiple improvements/fixes

addons/dialogic/Modules/Choice/subsystem_choices.gd
If a choice gets revisited, it errors because of connecting to the `BaseButton.pressed` again.
=> Fix Choice Buttons connecting too often

addons/dialogic/Modules/Text/subsystem_text.gd
When the speaker changes from a character to none, neither the `speaker_changed` signal changed nor the state info updated.
This changes the ternary to fall back to an empty string instead of `null`.
I am modifying my text whenever there is a valid speaker. I added a text event with a speaker and then a couple of text events without speakers.
However, the state info reported the same speaker for every text event.
I added documentation and adjusted the formatting of the function to be less tense and adhere to the Godot "newline per new section" mindset.
=> Fix Character Speaker changing

addons/dialogic/Modules/Text/subsystem_text.gd
When there was no `character` in the current state info, it would fall back to `null`.
Adds an empty string as fallback value.
This PR aims to fix #1923.
Therefore, I want to hear confirmation on the fixed behaviour.
=> Fix `null` assignment to `String`

addons/dialogic/Editor/CharacterEditor/char_edit_p_section_exports.gd, addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main_exports.gd, addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Example Assets/default_event.gd, addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd, addons/dialogic/Example Assets/portraits/simple_highlight_portrait.tscn, addons/dialogic/Modules/Character/default_portrait.gd, addons/dialogic/Modules/Character/default_portrait.tscn, addons/dialogic/Modules/Character/dialogic_portrait.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Jump/event_jump.gd, addons/dialogic/Other/DialogicUtil.gd
- fixes Importing portraits from folders
- moves a bunch of code into the DialogicPortrait class so simple custom portraits are easier to create.
- makes it so _unhighlight is called if noone speaks. 
- adds a example custom portrait scene that can highlight and bring the speaker to the front
=> Speaker highlight improvements

addons/dialogic/Modules/Audio/event_music.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd
The audio subsystem was setting the loop-property of the WAV audio stream which it didn't count as an error worth reporting but somehow REALLY didn't like, so it just refused to play the wav at all. 
This adds a check and removes the loop setting for wav files (from the visual editor).
=> Fix WAV music bug

addons/dialogic/Modules/Style/subsystem_styles.gd, addons/dialogic/Resources/dialogic_style.gd
The perpare() method should preload all the packed scenes needed for the particular style, thus fixing a lag-spike when first using that style. Needs to be called manually right now (e.g. `DialogicUtil.get_style_by_name("Textbubbles").prepare()`).
Hopefully fixes/improves lags when starting dialog (#1943)
=> Add prepare() method for styles that should preload scenes

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/dialogic_editor.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Other/DialogicResourceUtil.gd, addons/dialogic/Resources/event.gd
Previously the character picker of already opened timelines text event (visual editor) wouldn't become visible when adding the first character. This is now fixed.
=> Make sure character picker is updated when characters are added

.github/workflows/unit_tests.yml
This adds the `gdUnit4` framework as a single GitHub workflow CI file to the project.
It fires on new PRs and pushes.
However, I cannot properly test it without trying it once merged thought.
=> Add Unit Test GitHub Workflow

.github/workflows/unit_tests.yml
This broke downloading Godot for the CI.
=> Fix Godot version from `4.2.0` to `4.2`.

.github/workflows/resources/project.godot, .github/workflows/unit_tests.yml, addons/dialogic/Tests/Unit/test_example.gd
This PR fixes the unit test workflow by copying a `project.godot` file from `.github/workflows/resources/`.
Set the test folder to `addons/dialogic/Tests`.
=> Fix Unit Test CI

.github/workflows/unit_tests.yml
If there is a networking or permission issue but the tests succeeded, the workflow shall pass.
=> Prevent failure when report upload fails

.github/workflows/unit_test.yml, .github/workflows/unit_test_report.yml, .github/workflows/unit_tests.yml, addons/dialogic/Tests/Unit/test_example.gd
This uses two workflows. One per push/PR, uploading artefacts, and the other runs after the success of the first one, then publishes the test results.
=> Split workflows into two

addons/dialogic/Resources/timeline.gd
Reported by a user on discord, having an empty choice before an indentation change would incorreclty calculate the amount of end branches needed.
Example timeline of failure:
```
if {RedWandCount} > 0 or {BlueWandCount} > 0 or {GreenWandCount} > 0:
The pedestal is empty.
- Place red wand [if {RedWandCount} > 0][else="hide"]
- Place blue wand [if {BlueWandCount} > 0][else="hide"]
- Place green wand [if {GreenWandCount} > 0][else="hide"]
else:
The pedestal is empty and you can't do anything about it.
The end
[end_timeline]
```
Would fail previously, but now works.
=> Fix empty-choice-indentation bug

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/Events/EventBlock/event_right_click_menu.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_History/example_history_item.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_layer.gd, addons/dialogic/Modules/History/subsystem_history.gd, addons/dialogic/Modules/StyleEditor/style_editor.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Resources/dialogic_style.gd
I'm sorry I'm always making a bunch of different changes into a big PR.
This PR attempts to fix a few issues and does some other minor tweaks I've found necessary while experimenting.
- Add methods Dialogic.History.open_history() and Dialogic.History.close_history() that will emit open_requested and close_requested signals for any history layer to listen too (the default one does so now). fixes #1979
- fix for #1998
- fix for #1993
- fix for #1994
=> Multi-fix-PR

addons/dialogic/Modules/Audio/event_music.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd
Implements #2001 and fixes the background music event when its restarting the identical playing audio resource.
=> Add check preventing restarting the same audio resource.

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Modules/Background/event_background.gd
This tries (again) to improve the background event visual editor.
It also makes it so adding an event will always expand it.
Also tries to fix accidental dragging of events.
=> Visual editor improvements

addons/dialogic/Modules/Text/event_text.gd
This checks if a text event will be mistaken with another event and will add a \ at the beginning if so. 
This allows for characters like 
- doc
- ifraim
- labelgirl
- jumpboy
- etc.
- fixes #2016
=> Ensure characters can be escaped if they begin with event identifiers

addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
This allows CTRL+Clicking Characters and Timelines to open them instantly.
- works in visual editor and timeline editor
=> Add quick-open to timeline editors

.github/workflows/resources/project.godot, addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/Text/auto_advance.gd, addons/dialogic/Tests/Unit/test_auto_advance.gd, addons/dialogic/Tests/Unit/test_example.gd
Fixes Auto-Advance enabled until the next user input not ending on user input.
Fixes the PR https://github.com/dialogic-godot/dialogic/issues/2022.
This PR fixes unit tests relying on the Dialogic `autoload`.
=> Fix User Input Auto-Advance

addons/dialogic/Modules/Variable/subsystem_variables.gd
When setting a dialogic variable in code, it shows a bug here after `alpha 12`.
The method called `_set_value_in_dictionary` in `outside` as `VariableFolder` has been removed since commit [Variables Rework (second PR attempt) (#1972)](https://github.com/dialogic-godot/dialogic/commit/ccd5e3385db2366bcb8c7eb3702070eef25adedd)
I think this is a missing part.
=> fix a function bug in subsystem_variables.gd

addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.gd, addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.gd, addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.tscn
This PR extends `DialogicPortrait` on custom portraits in the custom assets.
This prevents errors when a method like `_highlight` is invoked.
=> Extend `DialogicPortrait` by custom portraits.

addons/dialogic/plugin.gd
This commit includes several changes to improve the readability and maintainability of the plugin.gd file:
1. More descriptive comments have been added to provide better context for the code.
2. Repeated code checking the existence of `editor_view` and `editor_view.editors_manager` has been moved into a helper function `_editor_view_and_manager_exist()`.
3. String literals that were used multiple times in the code have been replaced with constants to avoid magic strings and make future changes easier.
=> Refactor plugin.gd for improved readability and maintainability

addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd, addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd
This makes it so a custom portrait will auto-reload when it's script was changed. Unfortunately it's pretty hard to listen to a scene getting saved right now, but that will be implemented in the future, once it's easily doable.
Also makes sure the simple_highlight_portrait doesn't dim in editor.
=> Improve custom portrait workflow

addons/dialogic/Modules/Background/event_background.gd, addons/dialogic/Modules/Converter/settings_converter.gd
Tested the dialogic-1 converter today.  Noticed the change_timeline() to jump conversion needed touching up.  
Added a prep loop to populate a dictionary with timeline keys and file names to be able to populate the converted timeline to write out proper "jump nextTimeline/" in editor.
*Noticed the character position conversion for 2.0 now mirrors 1.x again.  Deleted the +1 in the code. 
**Committed a fix for conversion for an empty if-statement definition. https://github.com/dialogic-godot/dialogic/issues/1494
=> 1.x converter "jump" working by prep loop func + character "positions" debugged

addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd, addons/dialogic/Modules/Background/subsystem_backgrounds.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Choice/settings_choices.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/Clear/event_clear.gd, addons/dialogic/Modules/Core/subsystem_animation.gd, addons/dialogic/Modules/Core/subsystem_expression.gd, addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/History/subsystem_history.gd, addons/dialogic/Modules/Jump/subsystem_jump.gd, addons/dialogic/Modules/Save/subsystem_save.gd, addons/dialogic/Modules/Settings/subsystem_settings.gd, addons/dialogic/Modules/Style/subsystem_styles.gd, addons/dialogic/Modules/Text/auto_advance.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/TextInput/subsystem_text_input.gd, addons/dialogic/Modules/Variable/subsystem_variables.gd, addons/dialogic/Modules/Voice/subsystem_voice.gd, addons/dialogic/Modules/Wait/event_wait.gd, addons/dialogic/Modules/WaitInput/event_wait_input.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Other/DialogicUtil.gd, addons/dialogic/Other/Dialogic_Subsystem.gd, addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/TimelineResourceLoader.gd, addons/dialogic/Resources/dialogic_style.gd, addons/dialogic/Resources/event.gd
Subsystem Text
- hide_text_boxes() -> hide_textbox()
- show_text_boxes() -> show_textbox()
- can_skip_text_reveal() -> is_text_reveal_skippable()
- skip_text_animation() -> skip_text_reveal()
Subsystem Input
- stop() -> stop_timers()
=> Some method renames and code cleanup

addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Other/DialogicGameHandler.gd, addons/dialogic/Resources/timeline.gd
This is a first stab at solving #2028 by storing the index of the current text slice, and thus being able to correctly load in the middle of a text event. At least now when using New Lines as New Event option the loading will work correctly. 
Also introduces a method that makes sure events in timelines are fully disconnected from any methods. This just makes our lives a bit easier.
=> Add sub-Index for mid-text-event loading

addons/dialogic/Editor/CharacterEditor/character_editor.gd
Makes the code so that it should work in 4.2 (scripts only) and 4.3 (scripts+scene saves).
fixes #2017
=> Make sure custom portrait is reloaded when portrait scene is saved

addons/dialogic/Editor/Common/update_install_window.gd
get_tree() can return null when the Dialogic view isn't open but this function is being called by an external system. No node tree exists to wait for or manipulate, so errors are spammed.
=> Avoid null get_tree() call

addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd, addons/dialogic/Modules/Text/node_next_indicator.gd
Allow .tres assignment to NextIndicator so things like AnimatedTexture can be used and any other texture time.
Also made the TextureRect conditional checking more clear and consistent too.
=> Allow any Texture type to be assigned as NextIndicator icon

addons/dialogic/Modules/Text/node_dialog_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/plugin.cfg
Fixes a speed bug.
Changes Version Tag (remove WIP).
=> Pre alpha13 fixes

Tests/Resources/unit_test_character.dch, Tests/Unit/subsystem_text_test.gd, addons/dialogic/Modules/Glossary/glossary_editor.tscn, addons/dialogic/Modules/Text/subsystem_text.gd
In the case that a text line has no speaker or Dialogic is outside of a timeline, the `current_speaker` method crashes.
This PR handles invalid character values and returns `null`. On top, this adds unit tests.
=> Fix Current Speaker if nobody speaks

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Modules/Settings/event_setting.gd, addons/dialogic/Modules/Variable/event_variable.gd
Fixes #2067 
Fixes #2062 (Uses the proposed change in the issue)
May also fix #2063 , since I suspect a null value might be the product of the visual editor not generating the correct code
Changes
- Made _value_type reset the value and force an editor refresh on change
- Solves the issue of #2067 where changing the value type does not reset the value
- Refactor `event_variable` and `event_settings` to use enums for their different value types to make the code easier to read
- Refactor `event_block` to not call `set_value` on fields that are not visible. This prevents invisible fields from throwing errors when they get injected with the wrong data type in event nodes that have varying value types (such as `event_variable` and `event_settings`, whose value types can be strings, numbers, …
=> Fix variable and setting nodes not updating on type change

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Modules/Choice/ui_choice_end.gd, addons/dialogic/Modules/Condition/ui_condition_end.gd
Fixes #2064 
- Adds Undo/Redo support for choice and condition buttons (Buttons you click on below the nodes to create more of itself)
- Refactored event creating in `timeline_editor_visual.gd` to use a custom `add_event_undoable` function.
=> Add Undo/Redo for choice and condition buttons.

addons/dialogic/Core/DialogicGameHandler.gd
- Should fix #2069
Godot seemed to try to disconnect a signal we had already cleared (in timeline.clean()). Unfortunately it seemed pretty hard to differentiate these signals from other signals (because I wasn't allowed to access it's object). Luckily it is solved by simply waiting a frame because godot will have removed the connection on the next frame.
@Atlinx would love if you could try this!
=> Wait one frame before clean to avoid disconnecting internal ONESHOT connections

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
I'm pretty sure this isn't necessary anyways, but might be wrong. If we get leaked instances again (there is HUNDREDS of leaked StringNames all the time anyways), I will find a different solution.
=> Remove explicit timeline clear to fix #1996

addons/dialogic/Modules/Background/subsystem_backgrounds.gd, addons/dialogic/Resources/dialogic_style.gd
- fix style clone code which would result in an invalid packed scene for the base
- fix background_changed would not emit when no background holder was present. Having it emit anyways is nice, because then you can implement your own bg logic.
=> Small fixes

addons/dialogic/Modules/Style/subsystem_styles.gd
Function contained code with invalid syntax, and wrong variable return.
New code calls the method appropriately and makes a check for validity of the retrieved style.
=> Fix broken function `get_current_style` in Styles subsystem

addons/dialogic/Modules/Choice/event_choice.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd
This now makes the choice settings in the Settings tab simply the defaults, but they can be changed at runtime.
=> Improve choice subsystem by exposing most settings

addons/dialogic/Editor/Settings/csv_file.gd, addons/dialogic/Editor/Settings/settings_translation.gd, addons/dialogic/Editor/Settings/settings_translation.tscn
At the moment, the Test Locale in the Translation editor displays all possible locales.
This change will display all *unique* locales found in any of the CSVs.
=> Show used Locales in Test Locale Dropdown

addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
This PR sorts the names of the portraits alphabetically when importing portraits from a folder. Since the order of the portrait names in the timeline editor is based on the order of the portraits in the character editor, this helps to find the portrait you are looking for much faster when creating timelines.
Before & After:
=> [dialogic-1] Sort portraits when importing from a folder

addons/dialogic/Editor/Events/Fields/field_text_multiline.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Resources/timeline.gd
- Fix visual editor text event height calculation (#2091)
- Add syntax highlighting and CodeCompletion on multiline shortcode events
- Fix issue with multilines before choices
- Fix #2115
=> Fix multiline events, improve syntax highlighting and text event height calculation

addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/Settings/settings_general.gd
This identifier caused builds to breaks, as it does not exist at runtime outside the Godot editor.
Fixes: #2131 
Thanks to @lyuma for finding a workaround handling the `EditorInterface`.
=> Prevent `EditorInterface` breaking Builds

addons/dialogic/Modules/Glossary/glossary_resource.gd
Right now, if there is an alias key used in a glossary `Dictionary`, erasing encountered a type-match crash.
This will handle the `String` alias entry keys.
=> Add support for Alias Glossary Dictionary Keys

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd, addons/dialogic/Modules/Background/subsystem_backgrounds.gd, addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/Save/subsystem_save.gd, addons/dialogic/Modules/Voice/subsystem_voice.gd
There were numerous public methods, signals, and variables undocumented, resulting in hard-to-understand class reference.
The worst offender are the signals accepting a `Dictionary`, without documentation, they are opaque.
For reference, this is Dialogic's online class reference: https://docs.dialogic.pro/class_index.html
=> Add documentation to the `Background` and `Audio` subsystem

addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_icon.svg, addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/speaker-textbox-icon.svg, addons/dialogic/Modules/DefaultLayoutParts/Layer_TextInput/text_input_layer_icon.svg, addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/portrait_layer_icon.svg, addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
Fixes #2140 
**Changes**
- Layer icons are now forced to a maximum width of 32px (Scaled with editor scale)
- Adjusted some layer icons to make them more readable
- Expanded outlined layer icon svgs to make them appear consistent across different DPIs (Outlined svgs produce inconsistent results when scaled up)
- Height of each layer item is now forced to 32px (Scaled with editor scale)
- Ensures layer items without icons are the same height as layer items with icons
=> Fix style editor layer icon size

addons/dialogic/Editor/Events/Fields/field_condition.gd
Currently, `is_too_complex` requires `condition.count('==') == 1 and condition.count('>') != 1` etc for a condition to be complex, meaning you need something like `== != <= >=` in your expression for it to be counted as complex. This changes the requirement to being empty or having a single comparison operator, which is closer to what the simple condition editor and `complex2simple` use.
=> improve ConditionPicker#is_too_complex

addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd
Added `get_character_name_text` method to the text subsystem. This method evaluates and translates character's name and returns the final text that should be displayed. It's now used in the text event, character event, and in the `update_name_label` of the text subsystem.
Fixes #2127 
https://github.com/dialogic-godot/dialogic/assets/25368491/79452ce9-e4bc-4c39-a4e4-8bad22a6ca0c
=> Fix history not evaluating variables in names

addons/dialogic/Core/DialogicGameHandler.gd
this fixes a bug where starting a timeline in a callback attached to `Dialogic.timeline_ended` will lock, since `Timeline#clean` fires a frame after it's called (and after `timeline_ended` is emitted), which will then disconnect the signals on the _new_ timeline.
(easy repro:
```gdscript
func _ready():
Dialogic.start("whatever.dtl")
Dialogic.timeline_ended.connect(Dialogic.start.bind("whatever.dtl")
```
causes the timeline to run once, and then to start a second time without input working.)
=> don't emit `Dialogic.timeline_ended` until `Timeline#clean` has been called

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
When reloading the project, the right sidebar of the timeline editor does not remember its last manually set size.
This pull request saves the size as project setting, assigns the correct size to all relevant containers, and sets the proper event button style.
Closes #2152
=> Remember the Timeline Sidebar Size

addons/dialogic/Core/DialogicGameHandler.gd
Also removes the bool return value from clear() because it had no use.
=> Fix "timeline info could reset after new timeline was loaded"

addons/dialogic/Editor/Common/side_bar.tscn, addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Modules/Variable/variables_editor/variables_editor.gd
- Also fixes a wrong warning appearing when not renaming variables in the variable editor.
=> Add simple context menu to resource sidebar

addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_layer.gd
The history layer referenced the Dialogic autoload directly, which always results in an error on initial import of the plugin. This should remove that error, while working the same.
=> Remove direct Dialogic reference to avoid installation error

addons/dialogic/Editor/Events/Fields/field_text_multiline.gd, addons/dialogic/Editor/Events/Fields/field_text_multiline.tscn
Due to https://github.com/godotengine/godot/issues/80546 being fixed, we can remove some of our workaround code! Yay.
=> Remove dedundant text height calculation! Hurray!

addons/dialogic/Modules/Jump/event_label.gd, addons/dialogic/Modules/Jump/subsystem_jump.gd, addons/dialogic/Resources/event.gd
Label events can now be given a "display name", which can be translated. This way you can display the current story section, for example on a save.
The syntax for this is:
`label MyLabel (My Label Display Name)`
e.g.
`label Beginning (The beginning)`
Info about the last passed label can be accessed with Jump.get_lastl_label_identifier and Jump.get_last_label_name() (this might be translated).
- implements #1891
- Might be enough to consider #1918 fixed
=> Implement label display name (translatable) & store last label

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/CharacterEditor/character_editor_portrait_tree.gd, addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Core/subsystem_expression.gd, addons/dialogic/Modules/Text/event_text.gd
- should close #2199 
You can now use variables as portraits. You can also use expressions, for example if your character can have multiple genders, you could put those portraits in separate groups like this:
```
- male
- default
- happy
- sad
-female
- default
- happy
- sad
```
Then you can now use `{Player.gender}+"/happy"` as your portrait (assuming the Player.gender variable is either "male" or "female").
Note that this will be parsed when the portrait is set. It won't update the portrait live, in case you change the variable later, unless the portrait is set again with this expression!
- also stops duplicated portrait items from reporting name changes
- also adds a print_debug_moment() method to the DialogicGameHandler that allows to easily print the timeline and event for errors.
=> Allow expressions as portraits

addons/dialogic/Editor/Settings/settings_translation.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd, addons/dialogic/Modules/Glossary/glossary_resource.gd, addons/dialogic/Modules/Glossary/subsystem_glossary.gd
Moves some of the translation code for glossaries from the glossary layer into the glossary subsystem.
=> Simplify glossary translation code

addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/History/subsystem_history.gd, addons/dialogic/Modules/Wait/event_wait.gd
These were not working correctly because autoskip did a has_subsystem check before the history subsystem was initialized.
This might be breaking things for people who use the scene tree pausing for dialog, but that's just a bad use of it.
=> Fix to autoskip and wait event pausing

addons/dialogic/Modules/Audio/event_music.gd, addons/dialogic/Modules/Audio/event_sound.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd
The Music and Sound events will now default to "" as their bus, and when given an empty bus won't change the bus of the default_music_player or default_sound_player. 
This allows code like this, to change the default bus, without changing the event default:
`Dialogic.Audio.base_music_player.bus = "Music"`
*Same for sounds.*
Previously it would always default to the "Master" bus, except if you changed the event default. Assigning a default to the event in the modules manager still overwrites this. And both default audio players also still default to Master, so this does not break compat.
=> Audio event bus management simplification

addons/dialogic/Modules/Variable/event_variable.gd, addons/dialogic/Modules/Variable/subsystem_variables.gd
Improved documentation and implementation of `Dialogic.VAR.variable_was_set` and `Dialogic.VAR.variable_changed`.
The `variable_was_set` `info` now will consitently contain these keys:
```
```
- slightly compatibility breaking
=> Improve the variable_changed signals and their info dictionaries

addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/CharacterEditor/char_edit_section_general.gd, addons/dialogic/Editor/Common/DCSS.gd, addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/Common/toolbar.gd, addons/dialogic/Editor/Events/BranchEnd.gd, addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd, addons/dialogic/Editor/HomePage/home_page.gd, addons/dialogic/Editor/Settings/settings_general.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/editor_main.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Modules/StyleEditor/Components/StyleItem.gd, addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
The calculation of the margin based on the editor scale and the new godot editor theme were not properly set (used magic numbers).
=> Fixing relative margin scale

addons/dialogic/Resources/CharacterResourceLoader.gd, addons/dialogic/Resources/CharacterResourceSaver.gd
As #2234 , this just add very generic code to create an error handler on save/load of character resources (one of those already had half of one, I just updated it)
=> Update CharacterResourceLoader and CharacterResourceSaver.

addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/editors_manager.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd, addons/dialogic/Modules/Settings/event_setting.gd, addons/dialogic/Modules/Text/node_dialog_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/Variable/variables_editor/variable_tree.gd, addons/dialogic/plugin.gd
- Prevent autoload from constantly changing position in list
- Fix #2250
- Fix #2248
=> Multiple bug-fixes 

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/plugin.gd
This PR removes `dialogic_save` signal which is not emitted anywhere in the code.
=> Remove unused `dialogic_save` signal

addons/dialogic/Editor/Common/reference_manager.gd, addons/dialogic/Editor/Common/reference_manager.tscn
This PR adds a close button to the reference manager popup, so it looks like this in a window manager (like i3):
Fixes #2260.
=> Add close button to reference manager

addons/dialogic/Modules/Clear/event_clear.gd
class_name was DialogiClearEvent
Changed to DialogicClearEvent
=> Fix event_clear.gd class_name typo

addons/dialogic/Modules/History/subsystem_history.gd
_Hello everyone, did you miss me?_
Update variable type for _result instead of letting the engine guessing the type. 
For some reason in 4.3 (https://github.com/godotengine/godot/issues/92021 probably) can't guess the type of _that very specific line_, maybe because can't even parse the referenced class so it just throw it as variant and let it work until fails?
This _kinda_ works (as is just a solution in place that solved Emi traceback). Tested with https://github.com/dialogic-godot/test-project exporting to linux, using Godot v4.3.dev6.official [64520fe67].
It may fix https://github.com/dialogic-godot/dialogic/issues/2231 ? I'm not sure, that traceback seems more related to Editor* classes being referenced in exported game
=> Update subsystem history.

addons/dialogic/Modules/Choice/event_choice.gd, addons/dialogic/Modules/Choice/node_choice_button.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/History/subsystem_history.gd, addons/dialogic/Modules/Text/event_text.gd
This separates the choice showing logic into three parts (that can be used somewhat independantly of each other):
- Collecting question information (choice subsystem)
- Showing choices (choice subsystem)
- Loading choice info (choice node!)
This also adds logic to store visited choices in the already_visited history, and adds info on whether a choice has been visited to the choice_info dictionary. This should make it pretty easy to change the style of choices, when they have already been visited.
=> Improve choice logic

addons/dialogic/Modules/Text/subsystem_text.gd
Solution to the following issue: 
#2256 
This change takes `collect_character_names()` and sorts the collected names by length, descending, prior to compiling the regular expression. This allows longer nicknames containing display names to function as expected. (See #2256 for an example)
=> Ensure all names are highlighted despite length

addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.tscn
- fixes #1854
The search in the visual editor only searches inside text events, while the search in the text editor searches the whole document.
=> Implement search in timeline editors

addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Resources/character.gd
- Character Events now suggest characters already in the timeline first.
- Text Events now suggest characters already in the timeline first.
- Text Events now place the character from the most recent (relative to the text event) character event in the timeline first.
- Feature #1892
=> Better Character Suggestions!

addons/dialogic/Modules/Character/subsystem_portraits.gd
Makes sure speaker portraits DO appear when a speaker portrait was shown before.
Applies animation and fading to speaker portraits.
- fixes #2285 at least for me
=> Fixes for speaker portraits

addons/dialogic/Editor/Events/EventBlock/event_block.gd
This PR fixes the `tooltip` field of `display_info` being ignored (and hence not shown) for event block buttons, like the external link button to the variables editor:
=> Set tooltip for buttons in event blocks

addons/dialogic/Editor/Common/sidebar.gd
Every resource in Dialogic has a tooltip that shows its path in the file system, but timelines are different: they just show their name in the side bar. This PR makes that behavior consistent by displaying the timeline resource path as tooltip.
=> Set timeline resource tooltip to its path in side bar

addons/dialogic/Editor/Events/EventBlock/event_block.gd, addons/dialogic/Modules/Choice/event_choice.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Resources/event.gd
This changes the syntax of the choice event a bit:
```
- Choice Text | [if Condition] [shortcode="value"]
- Choice Text | [shortcode="value"]
- Choice Text
```
*The old syntax without | still works though.*
This also adds a new extra_data field to choices. This data will be provided to choice buttons so they can now be uniquely identified and given arbitrary information. This would be even cooler, if the dictionary field would be nicer looking. 
- fixes #2286
This also makes it so you have to press a button to enable the condition on choices, which looks much better. 
- fixes the UX problem #2272
This also fixes a bug with visual editor fields not having the correct value if they start hidden and are then revealed by a condition changing.
=> Choice event enhancements

addons/dialogic/Editor/HomePage/tips.txt
This PR fixes the "limiteless" typo in the tips.
=> Fix limitless typo

addons/dialogic/Resources/dialogic_layout_base.gd
Fixes #2305.
The `_apply_export_overrides` method is called by `apply_export_overrides`, though the latter is misspelled and cannot be called by `apply_scene_export_overrides` (in DialogicUtil.gd) since it checks if the method exists before calling it.
=> Fix misspelled apply_export_overrides method

addons/dialogic/Modules/DefaultLayoutParts/Layer_FullBackground/full_background_layer.tscn
This makes
- The BackgroundHolder color default to TRANSPARENT
- The FullBackgroundLayer not break when using right to left locale.
=> Fix for backgrounds

addons/dialogic/Modules/DefaultLayoutParts/Base_Default/default_layout_base.gd
This PR adds a `follow_viewport` property that is able to be changed through the layer settings under the styles tab. `follow_viewport` sets `follow_viewport_enabled` for `CanvasLayer` layout base scenes.
=> Export follow_viewport for default layout base

addons/dialogic/Core/DialogicResourceUtil.gd, addons/dialogic/Editor/editor_main.gd, addons/dialogic/Modules/Character/subsystem_containers.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Core/subsystem_animation.gd, addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/animations.gd, addons/dialogic/Modules/Text/auto_advance.gd, addons/dialogic/Modules/Text/auto_skip.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Modules/Wait/event_wait.gd
- fixes #1976
- fixes #2163
- fixes #2273
- fixes #2303
=> Various bug fixes

addons/dialogic/Modules/DefaultLayoutParts/Base_Default/default_layout_base.gd
Fixes the order of the `follow_viewport` export added by #2309. I'm sorry for the silly mistake!
=> Fix follow viewport export order

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Core/Dialogic_Subsystem.gd, addons/dialogic/Modules/History/settings_history.gd, addons/dialogic/Modules/History/settings_history.tscn, addons/dialogic/Modules/History/subsystem_history.gd, addons/dialogic/Modules/Text/event_text.gd
Simple and full event history can be toggled separately. If one option is enabled:
- Include that history in Dialogic.get_full_state() / Save.save().
- On Dialogic.load_full_state() / Save.load() replace that history with the history from the savegame.
- If the savegame doesn't contain that history, clear it.
- Events appended to the full event history between the clear_game_state() and the load_game_state() are dropped intentionally.
- On Dialogic.clear(FULL_CLEAR), clear that history.
The changes to the text event are needed to avoid duplicating the last entry in the simple history after a save+load. This also makes the text show up immediately after loading instead of the normal typing style.
Feel free to suggest a better option name or tooltip.
=> Add option to include simple and/or full event history in savegame

addons/dialogic/Modules/Core/subsystem_input.gd
On android, Godot triggers an `InputEventMouseButton` *in addition to* an `InputEventScreenTouch` and `Input.is_action_just_pressed(<mouse action>)` already returns true during the touch event. I don't have an ios device to test it, but I assume it would be the same there as well.
`subsystem_input.gd` currently handles the touch event in `_unhandled_input()` which makes the input catcher more or less meaningless on a touch device.
This PR will break projects with the setting `input_devices/pointing/emulate_mouse_from_touch` disabled unless they provide a custom input catcher or use `TouchScreenButton`s to convert touch into actions. I think thats's an acceptable tradeoff as such a setup also breaks touch input for many other controls like regular `Button`s.
=> input: Ignore InputEventScreenTouch

addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/textbox_with_speaker_portrait.tscn, addons/dialogic/Modules/DefaultLayoutParts/Style_SpeakerTextbox/speaker_textbox_style.tres
Style
- the input catcher is now behind the textbox by default
Layer:
- the textbox root setting is correctly setup (previously the hide_textbox setting on the wait/wait_input event didn't work)
- nothing except the text blocks the input now.
=> Improve SpeakerTextbox style and layer

addons/dialogic/Modules/Background/subsystem_backgrounds.gd
Should make it so that the background filtering follows the project default
- might fix #2322
=> Fix background filtering

addons/dialogic/Modules/Text/subsystem_text.gd
This had been completely broken... My bad.
It is now also improved to better handle {Variables.Some} {Expressions.some(2.x)} and [effect=so.me].
=> Fix and improve auto-pauses regex

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Resources/event.gd
The text event stores its state in `dialogic.current_state_info['text_sub_idx'] `which is needed for save+load to work correctly. Unfortunately it stays across a `Dialogic.clear()` (flags doesn't matter) so the first text event of a new timeline tries to resume in the middle of the event which would only work correctly directly after a `Dialogic.load_full_state()`.
Steps to reproduce the behavior:
1. Start the Visual Novel from dialogic-test-project.
2. Click on 'New Game'.
3. Textbox appears correctly.
4. Click the menu button and then the door button.
5. Click on 'New Game'.
6. Textbox is missing.
`clear_state()` is called on every `Dialogic.clear()` and also before the next event is executed so events can centralize their cleanup code. In case of a `Dialogic.load_full_state()`, it is …
=> Fix new text event getting stuck if Dialogic.start() is called during another text event

addons/dialogic/Modules/Character/DefaultAnimations/bounce.gd, addons/dialogic/Modules/Character/DefaultAnimations/fade_down_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/fade_up_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/shake_y.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_down_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_left_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_right_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_up_in.gd, addons/dialogic/Modules/Character/DefaultAnimations/zoom_center_in_out.gd, addons/dialogic/Modules/Character/class_dialogic_animation.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd
This renames DialogicAnimation `end_position` and `orig_position` (which where the same) to `base_position` and also adds `base_scale`. A slightly breaking change for people who made their own custom portrait animations.
It also adds an `await.process_frame` on change_speaker() when joining a character as it can happen that this is called before the textbox is shown and thus before the portrait container is correctly sized. This previously caused the speaker portrait to not work (just the first time when joining) when having a portrait-in animation setup.
Disables the non-functional signal `portrait_animating` for now until I find the time to make a proper re-implementation.
=> Cleanup portrait animations and fix speaker portrait slide-off

addons/dialogic/Editor/CharacterEditor/character_editor.tscn, addons/dialogic/Editor/editor_main.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/Clear/event_clear.gd, addons/dialogic/Modules/StyleEditor/style_editor.tscn
- Fix music keeps playing when layout is removed
- Fix clear event doesn't use time if step_by_step is false
- Fix choice crash (if last event and visited history is on)
- Fix visual separation in editor for g4.3
=> Multiple fixes

addons/dialogic/Editor/CharacterEditor/character_editor.gd
It now does a scan and identifies whether all the portraits have a common prefix, and if so, removes it from the portrait name.
Very nice if you import a bunch of portrait that all have e.g. the characters name as a prefix (which you wouldn't want in your portrait name).
=> Trim common prefix when importing portraits from folder

addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd, addons/dialogic/Editor/Inspector/inspector_plugin.gd, addons/dialogic/Editor/Inspector/timeline_inspector_field.gd, addons/dialogic/plugin.gd
This now shows a proper selection tool for timelines (a dynamic field like in the timelines) when doing `@export var tml: DialogicTimeline`
=> Add inspector field for timelines

addons/dialogic/Core/index_class.gd
A classic error.
When exported, scripts get converted to .gdc files. This means our silly silly .ends_with("gd") code won't find the animation script :(.
This should be a bit better.
=> Fix animations not found on export

addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd, addons/dialogic/Modules/StyleEditor/style_editor.gd, addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
When making a scene custom it would copy the scene and thus the resulting scene would share the same uid as the original. This would mess with styles created in the future. 
This PR should fix this by removing the UID when making a layer custom. 
I want to make the "make custom" code more modular and re-use it on the custom portrait logic to make sure this fix get's applied everywhere.
=> Fix UID issues on custom style layers

addons/dialogic/Modules/Character/node_portrait_container.gd
On the portrait container, debug portraits didn't show up at all because their export overrides where never loaded. This should now be fixed.
=> Fix debug portraits not showing up

addons/dialogic/Modules/Style/subsystem_styles.gd
This should be more intuitive in nearly all cases.
- fixes #2390
=> Styles: Preserve process_mode on style changes

addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
Closer to the script editors commenting behaviour:
- Only uncomments if ALL selected lines are comments (this also prevents erasing the beginning of lines)
- Preserves selection properly!
=> Text Editor: Improve CTRL+K commenting behaviour

addons/dialogic/Core/DialogicUtil.gd
There were STILL wrong uids in customized files. This should clean those up.
=> Core: More fixes for customizing files (follow up to #2387)

addons/dialogic/Modules/Variable/variables_editor/variables_editor.tscn
The RightClick menu showed up in the top left of the editor each time the editor was started because `visible` was set to `true`. This fixes that so the menu doesn't show up by default.
=> Make variable editor right click menu hidden by default

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
May fix #2381  but don't know for sure yet.
Regardless, this gets rid of some potential error spam that isn't useful to the end-user.
Sometimes the `opener_events_stack` items can be in the process of being freed, or have become Null by the time the code got there and causes an error trying to feed them into the `create_and_branch_event()` function.
Same with the `_batches` content.
=> handle some null/freed item cases to avoid bugs

addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
Fixes an error when using the Play Timeline button when you have a signal event that uses a `Dictionary` instead of a `String`.
=> Fix test timeline scene error with Dictionary signal event

addons/dialogic/Modules/Wait/event_wait.gd
Closes: #1029 
Added a skippable option to the wait event. Default value is false. I don't think that the `is_instance_valid` is needed for the `if _is_instance_valid(_tween):` but I put it there just in case.
=> Add skippable option to Wait event

addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/Settings/settings_general.gd
A stray print statement was leftover from a recent merge, so I removed it.
The Extension Creator's setup mode had two options reversed. Selecting `Event+Subsystem` would only create an event and `Subsystem only` would create both an event and subsystem.
=> Remove stray print statment, fix extension creator mode

addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Jump/event_jump.gd, addons/dialogic/Modules/Text/event_text.gd
Fixes: #1059 
This implementation checks if the old value isn't valid first, and only then resets it and notifies the UI that it needs updating. If any other fields need this as well, let me know and I'll add them.
=> Fix event fields not reseting

addons/dialogic/Modules/Character/subsystem_containers.gd
Closes: #2443 
Based on conversation with @zaknafean, I checked how this was done in Dialogic 1, and it uses `get_viewport().get_visible_rect()`, which according to my testing does respect the window stretch mode in Project Settings.
More detailed testing may be required, I only tested that the size matches expectations based on the stretch mode settings of `disabled` and `canvas_items`. When set to `disabled` the size reflects the actual window size, but on `canvas_items` the viewport size is returned instead, regardless of the window size. If I have time for further testing I will post any results as well.
=> Fix portrait scaling

addons/dialogic/Modules/Character/node_portrait_container.gd, addons/dialogic/Modules/DefaultLayoutParts/Style_SpeakerTextbox/speaker_textbox_style.tres, addons/dialogic/Modules/DefaultLayoutParts/Style_TextBubbles/textbubble_style.tres, addons/dialogic/Modules/DefaultLayoutParts/Style_VN_Default/default_vn_style.tres, addons/dialogic/Modules/Style/subsystem_styles.gd, addons/dialogic/Modules/StyleEditor/style_editor.gd, addons/dialogic/Modules/StyleEditor/style_layer_editor.gd, addons/dialogic/Resources/dialogic_style.gd, addons/dialogic/Resources/dialogic_style_layer.gd
This is a big rewrite of how styles are stored in layers with the main goal of identifying styles not by their index but by an identifier. This solves a big issue that inherited styles previously had, where moving the layers of the base style was allowed but would break sub-styles. 
This also includes some code which auto-updates existing styles, but I'd like to remove this code again before we enter the beta phase (or at least for stable).
- fixes #2085
=> Styles: Rework internal structure of styles

addons/dialogic/Editor/CharacterEditor/character_editor_portrait_tree.gd
Maybe Fixes: #2372 
Added check to make sure something is selected when trying to create drag preview in the Character editor's Portrait tree. Also renamed some function arguments to avoid shadowing builtin `position` variable.
=> Fix portrait tree drag drop bugs

addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd
Discovered an issue where events would randomly teleport in the visual timeline when clicking too fast for the `_process` function to run. Additionally, sometimes the mouse position would be in the dead space between events causing `drag_to_position` not to get updated when `_process` did get called.
This fix ensures that `drag_to_position` has been updated at least once after starting a drag operation, otherwise cancels the drag on completion.
This was a pretty difficult bug to reproduce on my machine, but my tester has a very fast click and could consistently reproduce the issue, to the point where their timeline constantly was getting garbled.
=> Fix events teleporting around with fast mouse clicks

addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd, addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/Common/update_install_window.gd, addons/dialogic/Editor/Common/update_manager.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd, addons/dialogic/Modules/Character/default_portrait.gd, addons/dialogic/Modules/Character/settings_portraits.gd, addons/dialogic/Modules/Character/subsystem_containers.gd, addons/dialogic/Modules/Choice/node_choice_button.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/Clear/event_clear.gd, addons/dialogic/Modules/Core/subsystem_expression.gd, addons/dialogic/Modules/Core/subsystem_input.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/vn_portrait_layer.gd, addons/dialogic/Modules/Text/subsystem_text.gd
Character Names:
- Special symbols were now allowed, e.g. "???"
- Updates the regex continuously so that adaptive names like {Player.Name} can be autocolored.
Choices:
- New flag allows triggering the selected choice when the Advance action is pressed
Also removes various white-space lines
=> Text Subsystem: Improve autocolor names feature + Choice Subsystem: Allow using input action for choices

addons/dialogic/Modules/Character/event_character.gd
Using a Character Update Event to change both the portrait and extra data at the same time doesn't pass the extra data to the new portrait. This changes it so that the extra data gets set AFTER loading the new portrait (if there is one).
=> Set Extra Data after updating portrait in Character Update Event

addons/dialogic/Resources/event.gd
Small thing :) A fixed spelling mistake. Thank you for the addon!
=> chore: fix small spelling mistake in event documentation.

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Core/DialogicUtil.gd
This just sorts the subsystems alphabetically when reloading to make cleaner diffs when using extensions that add subsystems. Also rearranges the default order of subsystems in the `DialogicGameHandler.gd` file.
=> Sort subsystems for cleaner diffs

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
This change is for when you have multiple event blocks selected, and you want to just select one of them.
Previously, if you had multiple items selected and click on one of the already selected ones (without CTRL/SHIFT), nothing would happen. With this change, it will deselect the other items and only select the one you clicked on. This will only happen when you *release* the mouse button, and if you haven't started dragging. This makes the selection behave similarly to how filesystem selections usually work.
=> Make visual timeline deselect other items when selecting an already selected one

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Closes: #2455
Closes: #2407
When pasting into an empty timeline, the paste position would be set to -1, making the first item pop down to the end of the list.
=> Fix visual editor event copy/paste issues

addons/dialogic/Core/DialogicUtil.gd
I set the wrong type for the for loop index variable, should be Dictionary.
=> Fix wrong typing on sorting subsystems loop

addons/dialogic/Modules/Text/event_text.gd
By switching to a new speaker before changing the style, I solved the issue of overlapping portraits. This way, when changing the style, the object calling change_speaker is already the next speaker.
=> fix: portrait overlapping #2458 

addons/dialogic/Modules/HighlightPortrait/simple_highlight_portrait.gd
This portrait is simple and allows for only one image, there is no underlying node hierarchy that may need to change. Therefore, we need to ensure to not recreate a new character node.
We should look at handling this behaviour, to keep highlights working for other portrait scenes, that create a new character instance, too.
=> Fix instancing new Character Nodes on Simple Highlight Portrait

addons/dialogic/Resources/dialogic_layout_base.gd
Now persistent info is always merged with the previously stored info. This means switching to a non-textbubble style doesn't clear all registers.
=> Styles: Fix persistent info getting lost

addons/dialogic/Core/DialogicResourceUtil.gd
Godot ignores directories with a `.gdignore` file, but Dialogic still scans them.
In case of the android build template, Godot copies all files into `./android/build/assets` and the gradle build copies them again. In my case Dialogic had 3 copies of every timeline and every character. The name of those duplicates can change inside `project.godot` which is annoying for version control.
=> Ignore directories ignored by godot (.gdignore file)

addons/dialogic/Modules/Background/DefaultBackgroundScene/default_background.gd
Godot resource load works only for imported Resources and background changer accepted only res:// paths before. This change allows for an image from user:// path to also be used.
=> Feat: background file can now be loaded from user:// scope too

addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd
Now allows text effects and bbcode in the random selection:
```
<[b]Option 1 [/b] / [color=red]option 2[/color] / option 3>
```
The highlighting has also been fixed for these situations.
=> Improve random selection regex and highlighting

addons/dialogic/Core/DialogicResourceUtil.gd
Adding a label via gdscript will cause Dialogic to crash in `get_unique_identifier()` when attempting to `get_extension()` on a null `file_path`. This PR checks if it's null and returns `""`.
=> Fix crash when creating DialogicLabelEvent in gdscript

addons/dialogic/Modules/Choice/subsystem_choices.gd
This was missing, and the History Layer never displayed any Choices.
=> Add Choices to `last_question_info`.

addons/dialogic/Core/DialogicGameHandler.gd
If you use an exported variable with a path to a file (let's say a timeline):
`@export_file var timeline = ""`
Godot will automatically use a UID path (something like `uid://d0kqf1bb2ev0` instead of `res://timeline.dtl`) file to avoid having issues when moving that file in the future. This check in Dialogic is only expecting for the string `res://` in the argument, so if you do something like `Dialogic.start(timeline)` it will fail to run.
The fix just adds a check for UID as well. 
I suspect there are many other places where this is happening, so it would be good to replace all those instances of checking for "res://" to also check for "uid://"
=> Check for UIDs in strings as well on `start_timeline`

addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd
I was just browsing through the code, and noticed a small typo.
=> Fix a typo when applying italic font in text bubbles

addons/dialogic/Modules/Jump/event_jump.gd, addons/dialogic/Modules/Jump/subsystem_jump.gd
I noticed that the jump event could not be set to a variable. This pull request is to add that feature.
How to test:
1. create a dialogic variable in the default VAR folder.
2. create a timeline with a jump event with the name of the variable and have it jump pass an end time line event to a label with the name of what the variable is set too.
`jump {jump_demo}`
`Failed`
`[end_timeline]`
`label variable`
`Success`
3. Run the timeline. You should see the dialog that it jumped too.
=> Allows jump to be a variable, making the jump event dynamic

addons/dialogic/Modules/Character/subsystem_portraits.gd
I just replaced load(scene_path) with ResourceLoader.load_threaded_request(scene_path) and placed await in the code. Now, when scenes with characters are loaded, there are no freezes in the main thread. I used a complex custom scene with Spine animations and 4k atlas textures.
=> Added a multithreading loading

addons/dialogic/Resources/dialogic_layout_base.gd
Fixes #2526 by calling `_load_persistent_info()` in `_init()` instead of `_enter_tree()`. Previously, `_enter_tree()` was called the frame after `Dialogic.start()`, causing new changes (e.g., `register_character` to be overwritten with the old persistent info.
The fix here is more general than the one proposed in #2526 (which only addressed text bubbles). During testing `_init()` was called after `_exit_tree()`, so there should be **_no_** race conditions with saving and loading persistent info on the same frame.
=> Immediately load persistent info to prevent overwritting

addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd
The `await` on line 124 can take some time depending on if the textbox fades in or has an animation when opening, and because of that the `about_to_show_text` signal has a delay before the text begins to render.
Delay from before the await to after the await measured by `Time.get_ticks_msec()`
```gdscript
dialogic.Text.about_to_show_text.emit({'text':final_text, 'character':character, 'portrait':portrait, 'append': is_append})
print("About to await dialogic.Text.update_textbox %s" % Time.get_ticks_msec())
await dialogic.Text.update_textbox(final_text, false)
print("Done Awaiting dialogic.Text.update_textbox %s" % Time.get_ticks_msec())
```
If you use `about_to_show_text` to enable an animation, as an example for lip flaps, the delay makes it look awkward because mouth begins moving before …
=> Add Signal text_started that aligns with the text appearing

README.md, addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/Common/toolbar.gd, addons/dialogic/Editor/Settings/CoreSettingsPages/settings_general.tscn, addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Modules/Audio/event_audio.gd, addons/dialogic/Modules/Audio/subsystem_audio.gd, addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd
- Makes sure a missing/invalid audio file path doesn't result in a crash, just an error
- Small code cleanup
- Change textbubble layout slightly to reduce the movement on each new text.
- Remove some usage of dict.merged and disguise move CodeEdit.move_line_up/down() usage to keep 4.2 compatibility
- Bump minimum required version to 4.2.2
=> Fixes for 4.2, textbubble, missing audio files and cleanup

addons/dialogic/Modules/Choice/subsystem_choices.gd
Recently added this function to my own code base for something, thought it could be useful for OG codebase, the possibility of setting a different choice focus later after showing the question.
User could set this for example to be called after choices are shown by getting the signal question_shown.
```
Dialogic.Choices.focus_choice_button_node(button_index);
```
=> Added focus_choice_button_node function to Choices subsystem

addons/dialogic/Core/DialogicResourceUtil.gd
My game was strangely freezing when trying to trigger a timeline. I looked into the codebase and I found out this while loop on DialogicResourceUtil caused the issue.
```gdscript
static func add_resource_to_directory(file_path:String, directory:Dictionary) -> Dictionary:
var suggested_name := file_path.get_file().trim_suffix("."+file_path.get_extension())
while suggested_name in directory:
suggested_name = file_path.trim_suffix("/"+suggested_name+"."+file_path.get_extension()).get_file().path_join(suggested_name)
directory[suggested_name] = file_path
return directory
```
If file_path is `user://laura olsdal.dch` and directory is `{ ..., "laura_olsdal": "res://assets/characters/laura_olsdal/laura_olsdal.dch", ... }` the code enters an infinite loop. So I just made a little check to break …
=> fix: potential infinite loop on DialogicResourceUtil.gd

addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Core/DialogicResourceUtil.gd, addons/dialogic/Core/DialogicUtil.gd, addons/dialogic/Editor/CharacterEditor/character_editor.gd, addons/dialogic/Editor/Common/sidebar.gd, addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd, addons/dialogic/Editor/Events/Fields/field_options_fixed.gd, addons/dialogic/Editor/Inspector/timeline_inspector_field.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Modules/Character/event_character.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Jump/event_jump.gd, addons/dialogic/Modules/Jump/event_label.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Resources/character.gd, addons/dialogic/Resources/dialogic_identifiable_resource.gd, addons/dialogic/Resources/timeline.gd
This makes both `DialogicTimeline` and `DialogicCharacter` extend `DialogicIdentifiableResource` which basically adds a get_identifier and set_identifier method. If an identifier is set at runtime for a non-saved resource, the resource is registered to the directories directly (without a path) allowing for the use of those resources in timelines from then on.
```gdscript
var characterA := DialogicCharacter.new()
characterA.display_name = "Code Character"
characterA.color = Color.WEB_PURPLE
characterA.set_identifier("CodeCharacter")
var timelineA := DialogicTimeline.new()
timelineA.from_text(
"""
CodeCharacter: Timeline A!!!
jump CodeTimelineB/
label Section2
CodeCharacter: About to end timeline A.
""")
timelineA.set_identifier("CodeTimelineA")
var timelineB := DialogicTimeline.new() …
```
=> Improve runtime resources (timelines and characters created through code)

addons/dialogic/Editor/Common/ReferenceManager_AddReplacementPanel.gd, addons/dialogic/Editor/Common/reference_manager_window.gd, addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd, addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Editor/TimelineEditor/shortcut_popup.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.gd, addons/dialogic/Editor/TimelineEditor/timeline_editor.tscn
Ctrl+R now shows options to replace in the timeline editor (should work very close to the script editors implementation). It also has an option to add the replacement as an item in the Broken Reference Manager, which acts as a "Find and replace in all timelines" option.
=> Timeline Editor: Add Replace functionality to search

addons/dialogic/Modules/Style/subsystem_styles.gd
A very simple change. When switching between styles if the new applied style inherits the old one then the exports of the old style get transferred to the new one, this PR makes this also happen when both old and new styles inherit from the same style.
The use-case, at least in our case, was that we had a different style for each character in our game, so every time the characters switched in the dialogue the whole layer was destroyed and rebuilt, causing problems with the textbox animations. So we made all the styles inherit from one base style that way when we switch between styles the exports simply change, but we had the problem that when changing from a character style to a different character style since the second style technically didn't inherit from the first one it didn't work, …
=> Apply new overrides when switching styles if there's a common ancestor

addons/dialogic/Modules/Audio/subsystem_audio.gd
just more specific node types, not a big deal
=> fix the node type as AudioStreamPlayer

addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd, addons/dialogic/Modules/Choice/event_choice.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/Condition/event_condition.gd, addons/dialogic/Modules/Core/event_end_branch.gd, addons/dialogic/Resources/event.gd
Adjusts the branching logic. This should make the code a little easier to work with in the future hopefully.
- fixes #2558
This should get a bunch of testing, as if this isn't correct, that would be bad.
=> Events: Simplify logic for branching / end branches

Tests/Unit/subsystem_text_test.gd, addons/dialogic/Core/DialogicGameHandler.gd, addons/dialogic/Modules/Character/subsystem_portraits.gd, addons/dialogic/Modules/Text/event_text.gd, addons/dialogic/Modules/Text/subsystem_text.gd, addons/dialogic/Resources/dialogic_identifiable_resource.gd
- fixes several issues reported on the discord server
This code is defenitely breaking some compatibilty, because the speaker is now stored as an identifier and not as a resource_path in the current_state (breaks compat with old saves and maybe with some custom code of people). This is necessary to allow the speaker_update method to work with runtime-characters.
Could also break stuff because the order of operations in the text event has slightly been changed.
Also removed the unnecessary get_current_character method from the Portraits subsystem, as it just did the same as the Text systems method, and speaker is mostly a text concept anyways.
Fixed a dumb mistake in the dialogic_identifiable_resource
=> Improving/fixing issues with Speaker signal and Highlight methods

addons/dialogic/Modules/Character/DefaultAnimations/slide_down_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_left_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_right_in_out.gd, addons/dialogic/Modules/Character/DefaultAnimations/slide_up_in.gd, addons/dialogic/Modules/Character/class_dialogic_animation.gd
This changes the slide animations. Slide In/Out Left and Slide In/Out Right are now renamed to Slide From Left, Slide To Left, Slide From Right and Slide To Right. All the slide animations have been adjusted to slide exactly the needed amount so that the portrait fully leaves the screen, not just sliding a fixed amount. To do this, the animation class has gotten two new methods that help determening the animated nodes (e.g. Portraits) size and position.
This breaks compatibility because those animation names have changed.
=> Improve slide animations

addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd
By allowing the user to change the mouse filter, the bubble can now be set to ignore to prevent it from capturing events. The original use case for this modification was preventing bubbles of blocking the mouse movement when the mouse was captured on a 3D game.
Original issue: https://discord.com/channels/628713677239091231/1357374714263376035
=> Adds mouse filter to bubble

addons/dialogic/Modules/Choice/node_choice_button.gd, addons/dialogic/Modules/Choice/subsystem_choices.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.gd, addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.tscn
The choice buttons for the `Centered Choices` and `Textbubble Layer` layers can be replaced with a `PackedScene` descending from `DialogicNode_ChoiceButton`. This is intended for users who want custom behavior for their buttons (the choice must be pressed 3 times, on-hover animations, multi-`Control` UI, etc.).
**New Settings:**
_Centered Choices:_ `Choices/Behavior/Custom Button`, `Choices/Behavior/Maximum Choices`
_Textbubble Layer:_ `Choices/Behavior/Custom Button`, `Choices/Behavior/Maximum Choices`
**Changes to `DialogicNode_ChoiceButton`:**
The on-pressed behavior of the button can be customized by overriding `_pressed()`. By default, this preserves the existing behavior by emitting the new `choice_selected` signal when the button is pressed. The Choices Subsystem has now listens …
=> Choices: Add override for custom choice buttons
