- CREDITS.md
- addons/dialogic/Images/plugin-editor-icon.svg
- addons/dialogic/Images/plugin-editor-icon.svg.import
- addons/dialogic/dialogic.gd
> Add a proper editor icon to 0.5 branch

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/dialogic.gd
Related to #54 
This pottentially fix issue #53 , but since this is on a new branch, it has to be closed manually
> V1 performance fix

- addons/dialogic/Nodes/Portrait.gd
Use ResourceLoader.exists instead of Directory.file_exists to load image
Closes #90
> fix character loading path

- addons/dialogic/Nodes/dialog_node.gd
Adds the ability to show glossary definitions inside a question text.
This behaves exactly like in a classic text event
> Show glossary defs in questions

- README.md
- addons/dialogic/Nodes/dialog_node.gd
- addons/dialogic/Other/DialogicClass.gd
- addons/dialogic/Other/DialogicResources.gd
Updated the doc to reflect latest changes.
I added the doc inside the DialogicClass as well to make it easier for users.
There doesn't seem to be a way to generate clean documentation like in Java or javaScript, so I followed what I found in this PR: https://github.com/godotengine/godot/pull/41095
> Doc update

- README.md
- addons/dialogic/Other/DialogicClass.gd
I missed some typos, sorry about that
> fix doc typos

- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Other/DialogicResources.gd
This fixes #135 
~~Apparently, it also solves #136~~
Edit: It does not
> Character editor deletion fix

- README.md
- addons/dialogic/Dialog.tscn
- addons/dialogic/Nodes/dialog_node.gd
Will allow us to dynamically speed up/slow down/pause/etc. the timer in the future
> Replace the animation tween with a text timer

- addons/dialogic/Editor/Pieces/IfCondition.tscn
- addons/dialogic/Nodes/dialog_node.gd
This PR allows to use the name of a defintion to be used as a value in an IfCondition Event.
See Showcase:
https://streamable.com/ga4c4c
> [Proposal] use definition variables as if condition value

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/dialog_node.gd
> Add an option to use native buttons for choices

- addons/dialogic/Other/DialogicClass.gd
some functions were not marked as static, this pr fixes it
> fix non-static functions

- addons/dialogic/Nodes/dialog_node.gd
This PR makes the event loading process more consistent by creating utility functions and handling the dialog index only in those functions. This will help make debugging easier in the future.
> Simplify event loading

- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/EditorView.tscn
- addons/dialogic/Editor/MasterTree/MasterTree.gd
- addons/dialogic/Images/Context Menus/New.svg
> Add contextual menus to add timelines, characters, definitions and themes

- addons/dialogic/Editor/Events/CloseDialog.gd
- addons/dialogic/Editor/Events/CloseDialog.tscn
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Nodes/dialog_node.gd
> Add a duration spin box for the closing fade out  transition

- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/Events/ChangeBackground.gd
- addons/dialogic/Editor/Events/Common/Characters/CharacterAndPortraitPicker.gd
- addons/dialogic/Nodes/dialog_node.gd
More clear means mostly adding the [D] in front of them, so they don't get mistaken for something else.
> Deleted unnecessary debug prints and made other more clear

- addons/dialogic/Editor/Events/Choice.gd
- addons/dialogic/Editor/Events/Choice.tscn
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Nodes/dialog_node.gd
This PR adds conditions to choices just like in if branches.
The condition is hidden by default and can be activated with a checkbox.
This is still a draft as this hasn't been thoroughly tested, but it seemed to work on my minimal testing.
Closes #165
> Add conditions to choices

- addons/dialogic/Nodes/dialog_node.gd
> show choice buttons when text finishes

- addons/dialogic/Nodes/dialog_node.gd
> ignore empty text lines

- addons/dialogic/Nodes/dialog_node.gd
It's a small thing, but was annoyingly visible in the output console in your newest video @coppolaemilio.
> Removed print signal when choice buttons were created

- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
> Fix proposal "Selecting typing sound changes background" issue #346

- addons/dialogic/Editor/Events/Parts/Logic/EventPart_ConditionPicker.gd
- addons/dialogic/Editor/Events/Parts/Logic/EventPart_SetValuePicker.gd
> Fix typos in ConditionPicker and SetValuePicker

- addons/dialogic/Other/DialogicUtil.gd
Fixed issue where nested folders would delete contained files
> Fix for Issue #402

- addons/dialogic/Dialog.tscn
- addons/dialogic/Documentation/Content/Changelog.md
- addons/dialogic/Editor/Events/Parts/Audio/AudioPicker.tscn
- addons/dialogic/Editor/Events/Parts/Audio/AudioPickerComplex.tscn
- addons/dialogic/Editor/Events/Parts/Audio/EventPart_AudioPicker.gd
- addons/dialogic/Editor/Events/Parts/Audio/EventPart_AudioPickerComplex.gd
- addons/dialogic/Editor/Events/Parts/Audio/EventPart_VoiceEditor.gd
- addons/dialogic/Editor/Events/Parts/Audio/VoiceEditor.tscn
- addons/dialogic/Editor/Events/styles/SectionPanel.tres
- addons/dialogic/Nodes/CharacterVoice.gd
- addons/dialogic/Nodes/dialog_node.gd
This may be a bit of a hack, I'm sure there are more elegant ways of doing this.
But I think this should work just fine.
Let me know what you think.
> Implement start and stop time to charactervoice and audiopicker

- addons/dialogic/Dialog.tscn
- addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
- addons/dialogic/Editor/ThemeEditor/AudioPicker.tscn
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/TextBubble.gd
- addons/dialogic/Nodes/TextBubble.tscn
- addons/dialogic/Nodes/dialog_node.gd
- addons/dialogic/Nodes/random_audio_stream_player.gd
> Add audio picker and audio effects: wait, pass, hover, select

- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterAndPortraitPicker.gd
We count characters found and hide the event part if its 0
> Hide the character/portrait when no characters exist

- addons/dialogic/Editor/Events/CharacterLeave.tscn
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/CharacterAndPortraitPicker.tscn
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/CharacterJoining.tscn
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/CharacterPicker.tscn
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterAndPortraitPicker.gd
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterJoining.gd
- addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterPicker.gd
Adjusted Character Leave and Character join to prompt for character creation if no character exists.
> Hide the text event character picker if there are no character resources in the project #443

- addons/dialogic/Documentation/Content/Changelog.md
- addons/dialogic/Editor/ThemeEditor/default-theme.cfg
- addons/dialogic/Other/DialogicResources.gd
Copy the default theme to the themes folder on initialization
> Create visible theme for new projects

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/DialogNode.gd
- addons/dialogic/Nodes/canvas_dialog_node.gd
Propgated **text_complete** signal for testing and future functionality
Changed theme speed to be a float, stepped by .01
Cleaned up some tabbing in canvas_dialgog_node to match the rest of dialogic
> More range for dialog text speed #473

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
> Fixing wrong id for CTRL + T

- addons/dialogic/Parser/DialogicParser.gd
> Fixing empty display name bug

- addons/dialogic/Documentation/Content/FAQ/Signals.md
hope its okay if i opened 2 PR's for the same thing :/
I'm editing directly from github that's why , sorry !
make code highlighting and indentation correct
> fix code insertion in faq->Using Signals?

- addons/dialogic/Nodes/Background.gd
- addons/dialogic/Nodes/DialogNode.gd
> Fix crash when using Scene as Background

- addons/dialogic/Nodes/TextBubble.tscn
Another instance of tool + saving breaking things. Thanks godot.
> Fix broken TextBubble

- addons/dialogic/Editor/EditorView.tscn
- addons/dialogic/Editor/MasterTree/MasterTree.gd
- addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Localization/translation_service.gd
- addons/dialogic/Nodes/DialogicCustomEvents.gd
- Removed annoying print statements from CustomEvent script
- Removed some unnecessary preview calls on ThemeEditor load_theme -> increased Theme loading speed, at least for me ;)
> Small improvements

- addons/dialogic/Nodes/TextBubble.gd
The previous introduction of new commands unfortunately didn't work well with BBCode together. This is hopefully fixing that.
A kinda weird but seems to be working fix.
> Fixing BBCode and command indexing

- addons/dialogic/Nodes/DialogProxy.gd
Allows users to connect signals to dialogproxy as if it were the dialog node itself.
Handles copying of the signals on _ready
> Proxy signal proxy

- addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn
- addons/dialogic/Nodes/Background.gd
> Mode that doesn't stretch the background

- addons/dialogic/Documentation/Content/FAQ/CSharp.md
- addons/dialogic/Documentation/Content/FAQ/Portraits.md
- addons/dialogic/Documentation/Content/FAQ/Signals.md
- addons/dialogic/Documentation/Content/FAQ/can-i-use-dialogic-in-my-project.md
- addons/dialogic/Documentation/Content/FAQ/create-timeline-using-gdscript.md
- addons/dialogic/Documentation/Content/FAQ/how-to-make-dialog-show-up-in-game.md
- addons/dialogic/Documentation/Content/FAQ/resolution-small-dialog-big.md
- addons/dialogic/Documentation/Content/FAQ/why-not-graph-nodes.md
- addons/dialogic/Documentation/Content/Reference/000.md
- addons/dialogic/Documentation/Content/Reference/001.md
- addons/dialogic/Documentation/Content/Reference/Character.md
- addons/dialogic/Documentation/Content/Reference/Theme.md
Made a few improvements to the spelling and grammar across different areas of the documentation.
Fixes #667
> Documentation Improvements

- addons/dialogic/Editor/DocumentationViewer/DocumentationViewer.gd
- addons/dialogic/Editor/DocumentationViewer/DocumentationViewer.tscn
- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/EditorView.tscn
Also removed some funny wrong hints on toolbar buttons. Should fix #522
> Moving Docs Navigation Buttons to the toolbar

- addons/dialogic/Parser/DialogicParser.gd
If the regex finds a "[" somwhere before it (without a closing bracket in between, the name won't be colored to keep definitions working.
Fix for #651
PS: Also I made it so that empty nicknames won't cause the color tags in front of all messages.
> Name-coloring regex now checks for definition brackets

- addons/dialogic/Nodes/TextBubble.gd
Only instance of this making sense I found. Fix for #556
> Replace get_tree().create_timer() with $DialogicTimer

- addons/dialogic/Editor/Events/Parts/WaitSeconds/EventPart_WaitSeconds.gd
- addons/dialogic/Editor/Events/Parts/WaitSeconds/WaitSeconds.tscn
- addons/dialogic/Nodes/DialogNode.gd
> Add "Hide DialogBox" Option to Wait Seconds event

- addons/dialogic/Nodes/DialogNode.tscn
> Make choices no longer disable glossary by blocking the mouse

- addons/dialogic/Documentation/Content/Changelog.md
- addons/dialogic/Documentation/Content/FAQ/input.md
Updated the changelog for 1.4 WIP and added a short page about input (and Input Actions) because I've seen some confusion and questions about how to use them.
> Documentation Additions

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Parser/DialogicParser.gd
> Add warning to single end branch events and ignore them in the parser

- addons/dialogic/Editor/Events/Templates/EventBlock.gd
get_index() instead of.... well, whatever
> Simplify some code

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
> Make sure timeline editor load adds all events at the end

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
> Update so Mac-hotkeys work

- addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd
Removed a line that is no longer neccesary with the UI Revamp
> Removed obsolete line

- addons/dialogic/Nodes/DialogNode.gd
> Disable shortcut in choice button tooltip

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/DialogNode.gd
Should fix #640
New Setting is in Theme>Dialog Box>Behaviour
enabled by default
> Add option that toggles if portraits are behind or on top of text box

- addons/dialogic/Nodes/DialogNode.gd
Some leftovers from my first animation implementation that resulted in a crash.
> Fix the broken Close Dialog event

- addons/dialogic/Other/DialogicClass.gd
Fixes deeper level folder depth bugs not previously found in PR #748 before it got merged
> Timeline and Variable Folder searching bugfix

- addons/dialogic/Nodes/History.gd
- addons/dialogic/Nodes/History.tscn
Removed the signal and code associated with _on_HistoryPopup_item_rect_changed
> Removed _on_HistoryPopup_item_rect_changed

- addons/dialogic/Other/DialogicUtil.gd
Should fix some update issues where the join event wasn't working properly.
> Make sure "" is now saved as "Default" on join event

- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/EditorView.tscn
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn
- addons/dialogic/Editor/TimelineEditor/TimelineTestingScene.gd
- addons/dialogic/Editor/TimelineEditor/TimelineTestingScene.tscn
- addons/dialogic/Nodes/History.gd
- addons/dialogic/Other/DialogicClass.gd
Adds a button that allows to instanly play the current timeline.
- New Button in the toolbar (when a timeline is opened)
- New "Testing" scene
- prints the argument if it recieves a dialogic signal
- ends the game when the timeline ends
> Add easy way to play the current timeline

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/DialogNode.gd
- addons/dialogic/Nodes/Portrait.gd
> exposes the portrait fade time in the theme editor

- addons/dialogic/Editor/Events/Character.tscn
- addons/dialogic/Editor/Events/TextEvent.tscn
> Add/Fix TextEvent and CharacterEvent documentation links

- addons/dialogic/Documentation/Content/Reference/History.md
First roll of the history documentation
> History documentation

- addons/dialogic/Documentation/Content/Reference/History.md
Updated mainly grammar mistakes
> Grammar pass

- addons/dialogic/Nodes/Anima/DialogicAnimaPropertiesHelper.gd
- addons/dialogic/Nodes/Anima/animations/attention_seeker/bounce.gd
- addons/dialogic/Nodes/Anima/animations/attention_seeker/heartbeat.gd
- addons/dialogic/Nodes/Anima/animations/attention_seeker/pulse.gd
- addons/dialogic/Nodes/Anima/animations/attention_seeker/rubber_band.gd
- addons/dialogic/Nodes/Anima/animations/attention_seeker/tada.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_in_down.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_in_left.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_in_right.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_in_up.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_out_down.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_out_left.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_out_right.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/back_out_up.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/bounce_out.gd
- addons/dialogic/Nodes/Anima/animations/entrances_and_exits/bouncing_in.gd
- addons/dialogic/Nodes/Portrait.gd
This pull request aims to address #815 
- fix: consider node scale when tweening via Anima
- fix: support custom portrait scenes for tweening
- fix: support mirroring for custom portrait scenes
> Animation fixes for custom portrait scenes

- addons/dialogic/Editor/SettingsEditor/Scenes/HistorySettings.tscn
- addons/dialogic/Example Assets/History/HistoryBackground.tscn
- addons/dialogic/Example Assets/History/HistoryRow.gd
- addons/dialogic/Example Assets/History/HistoryRow.tscn
- addons/dialogic/Nodes/History.gd
HistoryRow now use the default theme
HistoryRow themeing can now be disabled
Default Background now matches default theme
> History Default theme adjustments

- addons/dialogic/Localization/dialogic.csv
The existing translation for German sounded a bit odd. As a native German speaker, I tried to make it a bit more natural sounding.
> 🗃️ improve German translation

- addons/dialogic/Editor/Events/Parts/Text/EventPart_TextEditor.gd
> Increase the text editor min width

- addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd
- addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn
Fixed the 'default' setting not appearing after you set it for hotkey choices
Fixed hotkey choice settings layout
Changed the default status of autofocus from true to false to better suit peoples needs
> Default settings adjustments

- addons/dialogic/Localization/translation_service.gd
Fixes custom events failing in android exports due to a glitch in the translation services script
> Fixes custom events breaking in Android exports

- addons/dialogic/Localization/translation_service.gd
Reverts coppolaemilio/dialogic#880
> Revert "Fixes custom events breaking in Android exports"

- addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn
- addons/dialogic/Nodes/DialogNode.gd
- addons/dialogic/Nodes/DialogNode.tscn
Added a touch button overlay that covers the whole screen by default, but is resizable if you just want part of the screen to be touch sensitive.
> A basic touch to advance implementation

- addons/dialogic/Localization/translation_service.gd
Reverts coppolaemilio/dialogic#882
> Revert "Update translation_service.gd"

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Resources/timeline.gd
- timelines/one call node event.tres
- timelines/saving from no file.tres
- timelines/two events.tres
> Editor-event

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/TextBubble.gd
- addons/dialogic/Nodes/TextBubble.tscn
Changed TextureRect in textbubble to a ninepatch rect
> Ninepatch support

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
- addons/dialogic/Nodes/DialogNode.gd
- addons/dialogic/Nodes/TextBubble.gd
Resolves this issue:
https://github.com/coppolaemilio/dialogic/issues/761
In action:
I think the margin and padding settings had some weirdness in the first place, so it's a little hard for me to say if I did a good job preserving functionality. The *box margin* is the margin from the textbox to the edge of the screen and the *text margin* is the margin between the textbox and the actual text within.
> Enable More Positional Control of Dialog Box

- addons/dialogic/Editor/Events/Parts/ResourcePickers/Files/EventPart_FilePicker.gd
File Picker now handles .tres and .res files too
> Added Godot Resources as a file pick type

- addons/dialogic/Nodes/DialogNode.gd
Moved where update_name occurs.
> Fixed bug where name was updated before theme was loaded

- addons/dialogic/Nodes/Portrait.gd
> Suppress the error for #866

- addons/dialogic/Nodes/DialogNode.tscn
Changed mouse filter so that Glossary hover works on questions
> Mouse Filter Fix

- addons/dialogic/Nodes/Anima/DialogicAnimaTween.gd
Added an instance valid check to avoid an occasional anima related crash. Fixes #982
> Guard against anima crash

- addons/dialogic/Editor/Events/EventNode/EventNode.tscn
> Move EventNode scene

- addons/dialogic/Editor/Events/EventNode/EventNode.tscn
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
> 2.0 Fix for dropping choice/condition

- addons/dialogic/Events/Text/Display_DialogText.gd
> 2.0 Add [br] modifier text command

- addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
- addons/dialogic/Editor/Common/Toolbar.gd
- addons/dialogic/Editor/Common/Toolbar.tscn
- addons/dialogic/Editor/EditorView.gd
- addons/dialogic/Editor/EditorView.tscn
- addons/dialogic/Editor/Events/EventNode/EventNode.gd
- addons/dialogic/Editor/Events/EventNode/EventNode.tscn
- addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Events/Call Node/event.gd
- addons/dialogic/Events/Character/event.gd
- addons/dialogic/Events/Choice/event.gd
- addons/dialogic/Events/Jump/event.gd
- addons/dialogic/Events/Music/event.gd
- addons/dialogic/Events/Sound/event.gd
- addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
- addons/dialogic/Events/Text/Settings_DialogText.gd
- addons/dialogic/Events/Text/event.gd
- addons/dialogic/Events/Variable/event.gd
Has been changed once more.
The suggestion function now expects more complex dictionaries. This allows to give more information, like tooltip, icon, etc.
This has been implemented on many events. Improved pickers can be found on:
- Text
- Character
- Jump
- Variable
Events can be expanded and collapsed with the tool icon.
Most events will hide their body by default (all except Text currently).
Double-clicking the event also expands/collapses the event.
The toolbar now has a ComplexPicker for selecting a recently used resource. Also changed the startup load behaviour to use that list and thus allow loading characters as well.
... when changing resource and having unsaved changes.
> 2.0 Editor Improvements

- addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
- addons/dialogic/Events/Choice/event.gd
- addons/dialogic/Events/Text/Subsystem_Text.gd
- addons/dialogic/Events/Text/event.gd
- indent works for more then two choices
- choices uses condition picker
- small fixes in Text event and Subsystem
> Small fixes

- addons/dialogic/Resources/TimelineResourceLoader.gd
Makes a small fix for the timeline loader.
> Fix TimelineLoader

- addons/dialogic/Events/Text/Subsystem_Text.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- addons/dialogic/Resources/TimelineResourceLoader.gd
- addons/dialogic/Resources/event.gd
I'll keep documentation about each one in here as I go along, but you can merge it in the morning and I'll open a new branch for more later
> 2.0 Various Speedup Improvemnets

- addons/dialogic/Events/Text/Subsystem_Text.gd
- addons/dialogic/Events/Wait/event.gd
Adds option to hide the text box while a wait is happening. defaults to true, as it did in 1.x
> 2.0 Wait time Hide Text property 

- addons/dialogic/Editor/Common/Toolbar.gd
- addons/dialogic/Editor/TimelineEditor/TimelineArea.gd
- also add filter argument to suggestions method of the Toolbar File Picker
> Fix Event Lines if Timeline ends with Question

- addons/dialogic/Events/Converter/Settings_Converter.gd
- addons/dialogic/Events/Variable/Subsystem_Variables.gd
- addons/dialogic/Events/Variable/event.gd
Fixing a few places where the inconsistent curly brackets for variables were catching in one way or another so they weren't working right
> 2.0 Variable Checking

- addons/dialogic/Nodes/TextBubble.gd
Delay showing nameplate until it is properly aligned
Co-Authored-By: meyaoigames <58981156+meyaoigames@users.noreply.github.com>
> Fix for Nameplate being unaligned

- addons/dialogic/Example Assets/Fonts/Overlock/Overlock.tres
Fixed a broken font reference
Co-Authored-By: ToddK <24928215+Todd-koeck@users.noreply.github.com>
> Fixed bad font reference

- addons/dialogic/Events/Character/Subsystem_Portraits.gd
- addons/dialogic/Events/Character/event.gd
- addons/dialogic/Events/Text/event.gd
- addons/dialogic/Resources/character.gd
> Fix character name getting lost

- addons/dialogic/Events/Background/DefaultBackground.gd
- addons/dialogic/Events/Background/DefaultBackground.tscn
- addons/dialogic/Events/Background/Display_Background.gd
- addons/dialogic/Events/Background/Subsystem_Backgrounds.gd
- addons/dialogic/Events/Background/event.gd
- addons/dialogic/Example Assets/ExampleScenes/DefaultDialogNode.tscn
- timelines/Chapter1.dtl
- DialogicNode_BackgroundHolder (CanvasLayer)
- DefaultBackground scene
- Background event now has separate `Scene` and `Argument` properties. If scene is empty, the default background scene is used (a TextureRect). Then the argument is the image. Otherwise the argument is a string. 
ToDo:
- testing
- changing importer/converter
> Background Fix/Improvements

- addons/dialogic/Editor/VisualEditor/VisualEditor.gd
everyting else seems fine but this one change
> Godot 4 Beta fixes

- addons/dialogic/Events/Text/CharacterEdit_TypingSounds_MoodItem.gd
> Fix hint_tooltip rename to tooltip_text

- addons/dialogic/Events/Converter/Settings_Converter.gd
> fix in converter for change in background event

- addons/dialogic/Resources/TimelineResourceSaver.gd
Okay, so there's something crazy going on with Godot that's still making the timeline saving wonky. the problem is every time a `FileAccess.WRITE' operation happens, it erases the contents of that file, so still randomly it was reported it *still* wasnt working right. I can't get it to replicate entirely, but sometimes at random Godot is just... Not finishing the save routine all the way through. So this adds a few more checks to the save routine, making the entire process of checks now happen in this order
1. checkes that any changes were made to begin with with the `timeline_not_saved` flag, since the Dialogic toolbar will otherwise just saving everything in the recent history list
2. makes sure the timeline didn't arrive with 0 events - as side effect of this, if youre deliberately …
> MOAR Timeline saving safety checks!

- addons/dialogic/Nodes/TextBubble.gd
Fix for #1272
Added code to resize the namelabel rect based on font size and string size.
> Nameplate alignment bug

- addons/dialogic/Nodes/History.gd
For issue https://github.com/coppolaemilio/dialogic/issues/1338
> Fix History.gd [br] resolve.

- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.tscn
All credit goes to @nathanhoad.
> Remake (copy paste, our old friend) text editor improvements

- addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
If you were in text editor mode, the timeline editor wouldn't show correctly after a restart.
Implemented custom syntax highlighting for the text editor.
> Improve syntax highlighting & Fix Text Editor reopening

- addons/dialogic/Editor/CharacterEditor/character_editor_tab_general.gd
- addons/dialogic/Editor/Common/sidebar.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
- addons/dialogic/Editor/editors_manager.gd
- addons/dialogic/Events/Audio/subsystem_audio.gd
- addons/dialogic/Events/Text/subsystem_text.gd
- addons/dialogic/Other/DialogicUtil.gd
Should fix:
- #1369
- #1368
- #1367
- #1364
- #1362
> Multiple smaller bug fixes

- addons/dialogic/Events/Character/event_character.gd
- addons/dialogic/Events/Text/event_text.gd
> Make text event regex not discard multilines

- addons/dialogic/Events/Character/subsystem_portraits.gd
This causes errors in current godot master.
> subsystem_portraits: Don't return null in functions that return void

- addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
- FIxes Broken Drag and drop functionality.
> Fix Drag and Drop + Choices moving crash

- addons/dialogic/Editor/Common/sidebar.gd
- addons/dialogic/Editor/Settings/settings_translation.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
- addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
- addons/dialogic/Editor/editors_manager.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- addons/dialogic/Other/Dialogic_Subsystem.gd
- addons/dialogic/Resources/TimelineResourceSaver.gd
- addons/dialogic/Resources/timeline.gd
Also removes unnecessary methods of the timeline resource.
Fixes #1439
Fixes #1408
> Fix add timeline button 

- addons/dialogic/Events/DefaultLayouts/Default/DialogicDefaultLayout.tscn
> Remove broken reference to Emi character

- addons/dialogic/Events/DefaultLayouts/ExampleHistoryScene.gd
> Add property groups and fix "no logs" crash

- addons/dialogic/Editor/Events/Fields/FilePicker.gd
- addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
- addons/dialogic/Events/LayoutEditor/layout_editor.gd
- addons/dialogic/Events/Text/subsystem_text.gd
- addons/dialogic/Other/DialogicGameHandler.gd
You can now actually set a custom layout scene that will be instanced in game and used for testing.
Also a crash bug introduced by the skip update is fixed.
> Fix for skippable bug and custom layout setting

- addons/dialogic/Events/DefaultStyles/Default/DialogicDefaultLayout.gd
- addons/dialogic/Events/DefaultStyles/Default/DialogicDefaultLayout.tscn
- addons/dialogic/Events/LayoutEditor/layout_editor.gd
- addons/dialogic/Other/DialogicUtil.gd
Also adds a vector field for the layout customizer.
- fix for #1456
> Add dialog box size setting and name label alignment

- addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.gd
- addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.tscn
Some methods and properties changed since this was last looked 
- fixes #1557
> Fix example portrait animated sprite (#1557

- addons/dialogic/Editor/Settings/settings_general.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
- addons/dialogic/Example Assets/default_event.gd
- addons/dialogic/Modules/Audio/event_music.gd
- addons/dialogic/Modules/Audio/event_sound.gd
- addons/dialogic/Modules/Background/event_background.gd
- addons/dialogic/Modules/CallNode/event_call_node.gd
- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/Modules/Character/event_position.gd
- addons/dialogic/Modules/Choice/event_choice.gd
- addons/dialogic/Modules/Comment/event_comment.gd
- addons/dialogic/Modules/Condition/event_condition.gd
- addons/dialogic/Modules/Core/event_end_branch.gd
- addons/dialogic/Modules/End/event_end.gd
- addons/dialogic/Modules/Glossary/event_glossary.gd
- addons/dialogic/Modules/History/event_history.gd
- addons/dialogic/Modules/Jump/event_jump.gd
- addons/dialogic/Modules/Jump/event_label.gd
- addons/dialogic/Modules/Save/event_save.gd
- addons/dialogic/Modules/Signal/event_signal.gd
- addons/dialogic/Modules/Style/event_style.gd
- addons/dialogic/Modules/Text/event_text.gd
- addons/dialogic/Modules/TextInput/event_text_input.gd
- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/Modules/Voice/event_voice.gd
- addons/dialogic/Modules/Wait/event_wait.gd
- addons/dialogic/Modules/WaitInput/event_wait_input.gd
- addons/dialogic/Resources/event.gd
This makes event categories strings and dynamically adds the sections in the button list. This allows extensions to add their own sections.
It also adds a way to reorder the sections in the settings.
> Make event categories more flexible

- addons/dialogic/Modules/Save/subsystem_save.gd
- addons/dialogic/plugin.cfg
- Changes the plugin version to Alpha 8
- Adds a default argument to Dialogic.Save.load()
> Fix version and add argument default 

- addons/dialogic/Modules/Converter/settings_converter.gd
I started testing it, but then I got to annoyed and just redid the whole (small project) so I still don't think this is fully working, just a bit better.
> Some fixes to the converter

- addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd
- addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn
- addons/dialogic/Modules/LayoutEditor/layout_editor.gd
> Expose next indicator settings to default layout customizer

- addons/dialogic/Modules/Glossary/subsystem_glossary.gd
This is a hacky fix for #1587.
Hopefully a better way will be found, as I can see this being a problem in other areas as well.
> Hacky way of fixing glossaries

- addons/dialogic/Other/DialogicUtil.gd
- Change function parameter from String type to Variant type
> Fixes #1606 logcial_convert function bug fix

- addons/dialogic/Modules/End/event_end.gd
fix https://github.com/coppolaemilio/dialogic/issues/1628
> Fix error in DialogicEndTimelineEvent

- addons/dialogic/Nodes/DialogNode.gd
Fixed Boolean logic in update character scene for custom portraits 
Added a couple missing portrait changed triggers
> Dialogic 1.5 final fixes

- addons/dialogic/Modules/Text/subsystem_text.gd
- addons/dialogic/Modules/WaitInput/event_wait_input.gd
> Clear text state when hiding textboxes

- addons/dialogic/Other/DialogicGameHandler.gd
> Prevent crash when accessing freed layout scene

- addons/dialogic/Modules/Audio/event_music.gd
- addons/dialogic/Modules/Audio/event_sound.gd
- addons/dialogic/Modules/Background/event_background.gd
- addons/dialogic/Modules/CallNode/event_call_node.gd
- addons/dialogic/Modules/Comment/event_comment.gd
- addons/dialogic/Modules/End/event_end.gd
- addons/dialogic/Modules/History/event_history.gd
- addons/dialogic/Modules/Jump/event_jump.gd
- addons/dialogic/Modules/Jump/event_label.gd
- addons/dialogic/Modules/Jump/event_return.gd
- addons/dialogic/Modules/Save/event_save.gd
- addons/dialogic/Modules/Settings/event_setting.gd
- addons/dialogic/Modules/Signal/event_signal.gd
- addons/dialogic/Modules/Style/event_style.gd
- addons/dialogic/Modules/TextInput/event_text_input.gd
- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/Modules/Voice/event_voice.gd
- addons/dialogic/Modules/Wait/event_wait.gd
- addons/dialogic/Modules/WaitInput/event_wait_input.gd
- addons/dialogic/Other/DialogicUtil.gd
> Modified events color palette

- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
This small bug was preventing the timeline editor to not load properly.
> Small shortcut bug fix

- addons/dialogic/Modules/Character/DefaultAnimations/bounce.gd
- addons/dialogic/Modules/Character/DefaultAnimations/bounce_in.gd
- addons/dialogic/Modules/Character/DefaultAnimations/bounce_out.gd
- addons/dialogic/Modules/Character/DefaultAnimations/fade_in_up.gd
- addons/dialogic/Modules/Character/DefaultAnimations/fade_out_down.gd
- addons/dialogic/Modules/Character/DefaultAnimations/heartbeat.gd
- addons/dialogic/Modules/Character/DefaultAnimations/shake_x.gd
- addons/dialogic/Modules/Character/DefaultAnimations/shake_y.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_in_down.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_in_left.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_in_right.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_in_up.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_out_down.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_out_left.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_out_right.gd
- addons/dialogic/Modules/Character/DefaultAnimations/slide_out_up.gd
- addons/dialogic/Modules/Character/DefaultAnimations/tada.gd
- addons/dialogic/Modules/Character/DefaultAnimations/zoom_in.gd
- addons/dialogic/Modules/Character/DefaultAnimations/zoom_in_center.gd
- addons/dialogic/Modules/Character/DefaultAnimations/zoom_out.gd
- addons/dialogic/Modules/Character/DefaultAnimations/zoom_out_center.gd
- addons/dialogic/Modules/Character/event_character.gd
Adds In/Out:
- slide_in_left
- slide_in_right
- slide_in_down
- slide_in_up
- zoom_in
- zoom_in_center
(and all out counterparts)
Adds Attention Seakers:
- bounce
- shake_x
- shake_y
> Add new animations

- addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Modules/Audio/event_music.gd
- addons/dialogic/Modules/Audio/event_sound.gd
- addons/dialogic/Modules/CallNode/event_call_node.gd
- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/Modules/Character/index.gd
- addons/dialogic/Modules/Choice/event_choice.gd
- addons/dialogic/Modules/Comment/event_comment.gd
- addons/dialogic/Modules/Condition/event_condition.gd
- addons/dialogic/Modules/Jump/event_jump.gd
- addons/dialogic/Modules/Jump/event_label.gd
- addons/dialogic/Modules/Jump/event_return.gd
- addons/dialogic/Modules/Settings/event_setting.gd
- addons/dialogic/Modules/Text/event_text.gd
- addons/dialogic/Modules/Text/index.gd
- addons/dialogic/Modules/TextInput/event_text_input.gd
- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/Modules/Wait/event_wait.gd
- addons/dialogic/Modules/WaitInput/event_wait_input.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- addons/dialogic/Resources/event.gd
- adds code completion for character event shortcodes.
- adds correct code completion for character animations
- will also remove already used (in that line) parameters from code completion suggestions.
- fixes #1671
- moves all event specific syntax highlighting and code completion into the event scripts.
> Add code completion for character event shortcodes

- addons/dialogic/Modules/CallNode/event_call_node.gd
- addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
- addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
- addons/dialogic/Modules/DefaultLayouts/Default/ExampleGlossaryPopup.gd
- addons/dialogic/Modules/DefaultLayouts/Default/animations.gd
- addons/dialogic/Modules/DefaultLayouts/Default/autoadvance_indicator.gd
- addons/dialogic/Modules/Text/subsystem_text.gd
Fix for #1680 and #1616 and #1688
Also added other quality of life improvements on the default layout
> Fix for #1680 and #1616 and #1688

- addons/dialogic/Editor/editors_manager.gd
> Remove invalid symbols from file names before creation

- addons/dialogic/Modules/Converter/settings_converter.gd
Corrected NodePath to "Begin Conversion" button.
> NodePath Correction

- addons/dialogic/Modules/Text/node_next_indicator.gd
> Fix next indicator texture not being loaded

- addons/dialogic/Editor/Settings/settings_modules.gd
- addons/dialogic/Modules/Audio/event_music.gd
- addons/dialogic/Modules/Audio/event_sound.gd
- addons/dialogic/Modules/Audio/subsystem_audio.gd
- addons/dialogic/Modules/Background/event_background.gd
- addons/dialogic/Modules/Background/subsystem_backgrounds.gd
- addons/dialogic/Modules/CallNode/event_call_node.gd
- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/Modules/Character/event_position.gd
- addons/dialogic/Modules/Character/subsystem_portraits.gd
- addons/dialogic/Modules/Choice/event_choice.gd
- addons/dialogic/Modules/Core/event_end_branch.gd
- addons/dialogic/Modules/Glossary/event_glossary.gd
- addons/dialogic/Modules/History/event_history.gd
- addons/dialogic/Modules/Jump/event_jump.gd
- addons/dialogic/Modules/Jump/event_return.gd
- addons/dialogic/Modules/Jump/subsystem_jump.gd
- addons/dialogic/Modules/Style/event_style.gd
- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Modules/Text/event_text.gd
- addons/dialogic/Modules/TextInput/event_text_input.gd
- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/Modules/Voice/event_voice.gd
- addons/dialogic/Modules/Wait/event_wait.gd
- addons/dialogic/Modules/WaitInput/event_wait_input.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- addons/dialogic/Resources/event.gd
- make event.expand_by_default false by default
- fix jump issue when auto returning at timeline end (mistake from RETURN addition)
- style base_style info not updating when changing style through add_layout_style()
- rename reset_portrait_positions to reset_all_portrait_positions to be more different from reset_portrait_position
- add has_background() method to Backgrounds Subsystem and has_music() to audio subsystem
- add missing safety check to modules page
> Multiple improvements and fixes

- addons/dialogic/Modules/Text/event_text.gd
Caused massive slowdowns due to constantly scanning the whole file system.
> Fix heavy visibility condition

- addons/dialogic/Modules/Core/subsystem_expression.gd
I added a method to the "Core Methods" section of the expression subsystem in order to implement regex pattern matching for use in things like conditions, etc.
Not super sure if I did this correctly. I wasn't able to push a new branch, so I forked and then am wanting to merge my fork's branch into dialogic? It's all a bit confusing!
> Added method to allow for using regex in expressions

- addons/dialogic/Editor/Common/reference_manager.gd
- addons/dialogic/Editor/Common/reference_manager_window.gd
- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/Modules/Converter/settings_converter.gd
- addons/dialogic/Modules/Settings/event_setting.gd
Join = join
Leave = leave
Update = update
Setting = setting
This will break compatibility for people already using the alpha. However it's easy to replace all instances with the BrokenReferenceManager.
> TextSyntax: Make Join, Leave, Update, Setting lowercase

- addons/dialogic/Modules/Character/subsystem_portraits.gd
- addons/dialogic/Modules/Text/event_text.gd
> Fix portrait animation pausing and signal error

- addons/dialogic/Modules/Character/subsystem_portraits.gd
> Make speaker portrait react to [portrait] effect

- addons/dialogic/Other/DialogicUtil.gd
Damn the godot devs trying to remove Editor stuff from the exports...
> Fix another export problem

- addons/dialogic/Editor/Common/side_bar.tscn
- addons/dialogic/Editor/Common/sidebar.gd
- addons/dialogic/Editor/Common/update_install_window.gd
- addons/dialogic/Editor/Common/update_install_window.tscn
- addons/dialogic/Editor/Common/update_manager.gd
- addons/dialogic/Editor/HomePage/home_page.tscn
- addons/dialogic/Editor/editor_main.gd
- addons/dialogic/Editor/editor_main.tscn
Most of the functionality is copied from DialogueManager.
- fixes #1008
> Implement Version Checker and Downloader

- addons/dialogic/Modules/Text/event_text.gd
- addons/dialogic/Modules/Text/node_type_sound.gd
- addons/dialogic/Other/DialogicUtil.gd
> Fixes for TypingSounds

- addons/dialogic/Modules/Variable/subsystem_variables.gd
Makes the code simpler and fixes some issues when trying to type expressions inside of text events.
> Improvements to get_variable and set_variable

- addons/dialogic/Editor/Common/update_install_window.gd
- addons/dialogic/Editor/Common/update_install_window.tscn
- addons/dialogic/Editor/Settings/settings_editor.gd
- addons/dialogic/Editor/Settings/settings_page.gd
- addons/dialogic/Editor/editor_main.gd
- addons/dialogic/Editor/editors_manager.gd
- addons/dialogic/Modules/Background/subsystem_backgrounds.gd
- addons/dialogic/Modules/Core/subsystem_expression.gd
- addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
- addons/dialogic/Modules/Style/event_style.gd
- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Modules/Text/node_type_sound.gd
- addons/dialogic/Modules/Variable/subsystem_variables.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- fixes TypeSound preview in editor (bug)
- fixes loading saves (bug)
-> The Style/Layout will now be loaded first. This makes sure the other subsystems can actually load their content. Some additions have been made to fix wrong expectations made by some subsystems.
- makes sure the correct defaults are used by the DefaultLayout
- removes a lot of trailing whitespace
> Multiple fixes: Saving, Layouts, TypeSounds

- addons/dialogic/Other/DialogicGameHandler.gd
> Small fix to handle_event in DialogGameHandler

- .gitignore
- addons/dialogic/Editor/CharacterEditor/char_edit_p_section_exports.gd
- addons/dialogic/Editor/CharacterEditor/char_edit_p_section_layout.gd
- addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
- addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main_exports.gd
- addons/dialogic/Editor/CharacterEditor/char_edit_section_portraits.gd
- addons/dialogic/Editor/CharacterEditor/character_editor.gd
- addons/dialogic/Editor/CharacterEditor/character_editor_main_settings_section.gd
- addons/dialogic/Editor/CharacterEditor/character_editor_portrait_settings_section.gd
- addons/dialogic/Editor/Events/Fields/Number.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Modules/Character/default_portrait.gd
- addons/dialogic/Modules/Choice/node_choice_button.gd
- addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Modules/Text/character_settings/character_moods_settings.gd
- addons/dialogic/Modules/Text/subsystem_text.gd
- addons/dialogic/Other/DialogicGameHandler.gd
- addons/dialogic/Resources/TimelineResourceSaver.gd
- Improve DGH script
- Clean up character editor scripts
- fix #1830
- fix #1817
> Multiple improvements

- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/plugin.cfg
Last small bug fix, and version adjustments.
> Pre-Alpha-11-Adjustments 

- addons/dialogic/Modules/Character/subsystem_portraits.gd
> Fix portrait mirror & [portrait] effect

- addons/dialogic/Editor/MasterTree/MasterTree.gd
> Fixed error on button clicks

- addons/dialogic/Editor/SettingsEditor/Scenes/HistorySettings.tscn
Fixed character leaves not logging properly.
The character leaves setting was incorrectly mapped to the 'scroll to bottom' setting. This has been fixed.
> Fixed character leaves in History

- addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
- addons/dialogic/Other/DialogicUtil.gd
Theme duplicate works, but subfolders on Theme remain broken. Folder issues are big enough separate issue to split this off.
> Themes now duplicate

- addons/dialogic/Editor/Events/LabelEvent.tscn
- addons/dialogic/Editor/Events/Parts/Logic/EventPart_LabelSetter.gd
Labels now generate unique ids
> Label anchors now id uniquely

- README.md
> Fix "Getting Started" in README

- addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
There was a bunch of leaked resources/nodes from this.
> Make sure to free layer scenes used in editor

- addons/dialogic/Modules/Background/subsystem_backgrounds.gd
- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Other/DialogicGameHandler.gd
> Restore loading a save when using Styles (#1959)

- addons/dialogic/Editor/Images/Pieces/warning.svg.import
- addons/dialogic/Modules/Character/update_mirror.svg.import
- addons/dialogic/Modules/Character/update_portrait.svg.import
- addons/dialogic/Modules/Character/update_position.svg.2023_09_23_08_37_47.0.svg.import
- addons/dialogic/Modules/Character/update_position.svg.import
- addons/dialogic/Modules/Character/update_z_index.svg.import
- addons/dialogic/Modules/Choice/icon.svg.import
- addons/dialogic/Modules/Clear/clear_background.svg.import
- addons/dialogic/Modules/Clear/clear_characters.svg.import
- addons/dialogic/Modules/Clear/clear_music.svg.import
- addons/dialogic/Modules/Clear/clear_positions.svg.import
- addons/dialogic/Modules/Clear/clear_style.svg.import
- addons/dialogic/Modules/Clear/clear_textbox.svg.import
- addons/dialogic/Modules/Condition/icon.svg.import
- addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/speaker-textbox-icon.svg.import
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/portrait_layer_icon.svg.import
- addons/dialogic/Modules/History/definition.svg.import
- addons/dialogic/Modules/History/icon.svg.import
- addons/dialogic/Modules/Jump/icon_return.svg.import
- addons/dialogic/Modules/Save/icon.svg.import
- addons/dialogic/Modules/Settings/icon.svg.import
- addons/dialogic/Modules/Text/node_next_indicator_icon.svg.import
- addons/dialogic/Modules/WaitInput/icon.svg.import
I'm still getting complaints about the svg import settings. Hope these are better.
> Try new svg imports (again)

- addons/dialogic/Modules/Background/event_background.gd
> More BG event adjustments

- README.md
Enhanced the structure and visual appeal of the README.md file. Added a table of contents for easier navigation, centered the main title and image for visual appeal, and organized the sections in a more structured way.
>  Improve README.md Organization and Visual Appeal

- addons/dialogic/Editor/Events/BranchEnd.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
- addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.tscn
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.tscn
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.tscn
- addons/dialogic/Resources/character.gd
- addons/dialogic/Resources/timeline.gd
- fixes #2008
- fixes #2007
- fixes #2003
- partially adresses #1995
- also cleans up character and timeline resource scripts
> Multiple fixes

- addons/dialogic/Modules/Background/Transitions/class_dialogic_background_transition.gd
- addons/dialogic/Modules/Background/subsystem_backgrounds.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_FullBackground/full_background_layer.tscn
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/vn_portrait_layer.tscn
Should fix #2038 and a problem reported on discord
> Fix background transitions

- addons/dialogic/Modules/History/event_history.gd
- addons/dialogic/Modules/History/subsystem_history.gd
> Fix history event

- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Modules/Text/event_text.gd
> Allow specifying parent to add layout

- addons/dialogic/Modules/DefaultLayoutParts/Base_Default/default_layout_base.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_layer.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/speaker_portrait_textbox_layer.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd
- Also allows picking .tres files for fonts (this allows the use of font variations)
> Fix for broken italics-font setting on default textbox layers

- addons/dialogic/Core/DialogicGameHandler.gd
- addons/dialogic/Modules/End/event_end.gd
- addons/dialogic/Modules/Style/subsystem_styles.gd
- addons/dialogic/Resources/timeline.gd
Interrupting a timeline or starting one on the exact frame another timeline ends should now work.
- might fix #2095
- might fix #2088
As well as possibly issues faced by people on discord.
> Attempt at fixing the timeline clearing mistakes

- addons/dialogic/Core/DialogicGameHandler.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Modules/Audio/subsystem_audio.gd
- addons/dialogic/Modules/Text/event_text.gd
- addons/dialogic/Modules/Text/subsystem_text.gd
- addons/dialogic/Resources/timeline.gd
Currently playing around with rollback and as it is a bunch of rapidly saving & loading at weird moments I find a bunch of holes in the system.
> Saving-Loading improvements & Other things

- addons/dialogic/Modules/Call/event_call.gd
Adds support for `PackedScene`s to the Call event.
Unsure what the temporary Autoloads are, I left the PackedScene` support out for now.
> Support `PackedScene` in the Call Event.

- addons/dialogic/Modules/Save/subsystem_save.gd
Closes #2168 
This should mostly not break anything. The only scenario i can come up with that would be able to break is when people reuse the array returned by get_slot_names() to append non strings to it.
> Save subsystem: updated function API

- addons/dialogic/Core/DialogicResourceUtil.gd
- addons/dialogic/Core/DialogicUtil.gd
- addons/dialogic/Core/index_class.gd
- addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
- addons/dialogic/Editor/CharacterEditor/character_editor.gd
- addons/dialogic/Editor/Common/sidebar.gd
- addons/dialogic/Editor/Settings/csv_file.gd
- addons/dialogic/Editor/Settings/settings_modules.gd
- addons/dialogic/Editor/Settings/settings_translation.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd
- addons/dialogic/Modules/Glossary/glossary_editor.gd
- addons/dialogic/Modules/Save/subsystem_save.gd
- addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
- addons/dialogic/Resources/TimelineResourceLoader.gd
- addons/dialogic/Resources/event.gd
> Fix use of FileAccess.file_exists()

- addons/dialogic/Modules/Text/auto_advance.gd
> Fix autoadvance with delay = 0

- addons/dialogic/Modules/Character/subsystem_portraits.gd
> Prevent default portrait from spamming error

- addons/dialogic/Modules/Text/subsystem_text.gd
Moves multiple function calls into post_install().
> Fix subsystem dependencies bug #2222

- addons/dialogic/Editor/Common/hint_tooltip_icon.gd
- addons/dialogic/Editor/Events/EventBlock/event_block.gd
Make use of a color that exists in 4.2 and 4.3.
> Use "contrast_color_1" for now

- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/Modules/Variable/variables_editor/variable_tree.gd
Fix regression of Set Variable event always expecting a float.
Add some logic to prevent the "Variable Renamed, check ReferenceManager" on newly created variables/folders.
> Variable fixes

- addons/dialogic/Editor/Events/EventBlock/event_block.gd
- addons/dialogic/Editor/Events/Fields/field_color.gd
- addons/dialogic/Editor/Events/Fields/field_color.tscn
- addons/dialogic/Resources/event.gd
> Field Color for Event

- addons/dialogic/Modules/Text/manual_advance.gd
- addons/dialogic/Modules/Variable/event_variable.gd
- addons/dialogic/plugin.cfg
- Fix Set variable assignment
- Update Version
- Make manual advance state keys use a fallback
> Small fixes before alpha 14

- addons/dialogic/Editor/Common/DCSS.gd
- addons/dialogic/Editor/Common/toolbar.gd
- addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd
- addons/dialogic/Modules/Character/DefaultAnimations/shake_x.gd
- addons/dialogic/Modules/Character/DefaultAnimations/shake_y.gd
- addons/dialogic/Modules/Character/DefaultAnimations/tada.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_History/example_history_item.gd
- addons/dialogic/Resources/CharacterResourceLoader.gd
- addons/dialogic/Resources/CharacterResourceSaver.gd
- addons/dialogic/Resources/TimelineResourceLoader.gd
This PR removes all trailing whitespace (tabs, in this case) before end of line.
> Remove trailing whitespace before end of line

- addons/dialogic/Modules/Choice/event_choice.gd
This was a regex problem.
This commit also fixes the syntax highlighting.
> Fix choices with conditions that contain [ or ]

- addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd
- addons/dialogic/Modules/Text/settings_text.tscn
This PR fixes all "it's own" orthographic mistakes.
> Fix "it's own" mistakes

- addons/dialogic/Modules/Core/subsystem_input.gd
> Require exact input on keyboard/button inputs

- addons/dialogic/Core/DialogicUtil.gd
- addons/dialogic/Editor/Common/update_manager.gd
- addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
- addons/dialogic/Modules/Core/index.gd
- addons/dialogic/Modules/Core/subsystem_expression.gd
- addons/dialogic/Modules/Jump/event_jump.gd
- addons/dialogic/Modules/Text/subsystem_text.gd
This adds a modifier tag that allows choosing text based on a condition:
```
[if {Condition} Insert This Text / Otherwise This]
with the variation
[if {Condition} Insert This Text] # which would just assume to not insert anything otherwise.
```
/ and ] have to be escaped as `\/` and `\]` when inside the true- or false-text.
- fixes #2142
> Conditional Modifier Tag

- addons/dialogic/Core/DialogicResourceUtil.gd
- addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.tscn
- addons/dialogic/Modules/Text/event_text.gd
- Avoid error message when an empty string is given (SpecialResource)
- Fix #2220
- Remove custom minimum size on vn textbox layer
> More bug-fixes

- addons/dialogic/Modules/Character/event_character.gd
Incorrect parameters were suggested.
> Fix move_ parameters in character event suggestions

- addons/dialogic/Modules/Character/subsystem_portraits.gd
- addons/dialogic/Modules/Voice/subsystem_voice.gd
- fixes #2321
- fixes a bug reported on discord, where is_voiced() can throw an error.
> Add additional safety checks

- addons/dialogic/Editor/Common/sidebar.gd
I had made this last month, but seem to have forgotten to actually make a PR for it.
> Add a right-click action to copy the resource identifier to the sidebar

- addons/dialogic/Modules/Character/event_character.gd
- addons/dialogic/Modules/Core/subsystem_input.gd
- also fixes a warning of Variant assignment in subsystem_input
> Fix mirror and z_index not being saved on Join event

- addons/dialogic/Core/DialogicResourceUtil.gd
- addons/dialogic/Modules/Character/settings_portraits.gd
- addons/dialogic/Modules/Character/subsystem_portraits.gd
`Fade Up In`/`Fade In Out`/`Fade Down Out` is outdated. Change them to the new ones.
> fix default portrait animations

- addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
- addons/dialogic/Modules/Call/event_call.gd
This is a bit annoying but it works.
- fixes #2358
> Fix autocompletion in 4.3

- addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
> TestTimeline Scene: Fix incompatible type of default argument

- addons/dialogic/Modules/Character/subsystem_containers.gd
> CharacterEvent: Fix position/size not working correctly when joining

- addons/dialogic/Modules/Character/index.gd
- addons/dialogic/Modules/Character/subsystem_portraits.gd
Closes: #2388 
Usage:
`Bob: Hello.[extra_data=set Face/Happy] Nice to meet you too.`
If I'm missing anything, let me know and I'll add it.
> Add text effect for extra_data to Portraits subsystem

- addons/dialogic/Modules/HighlightPortrait/simple_highlight_portrait.gd
> Fixed indenting error

- addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
- addons/dialogic/Editor/TimelineEditor/shortcut_popup.gd
- addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
- addons/dialogic/Editor/TimelineEditor/timeline_editor.tscn
- addons/dialogic/Editor/editor_main.gd
Adds a shortcut cheat-sheet to the timeline editor.
https://github.com/user-attachments/assets/3c0cdbfc-d77e-414e-9414-5776d5c6271c
Also fixes #1382
> Add Timeline Shortcut Cheat Sheet

- addons/dialogic/Core/DialogicGameHandler.gd
> Make ending timeline not emit timeline_started signal
